audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Chad and Sara Huebener
  license_number:
  about_markdown: |
    We are excited at the opportunity to work on your behalf to help you sell and buy a home. We are ranked within the top 50 agents in Edina Realty companywide, and have received Edinaâ€™s highest award for successful client closings - the Chairman's Circle Award - multiple, consecutive years running. If you are looking for experienced agents to guide you through today's challenging real estate transaction, we can help! All appointments are confidential. We look forward to hearing from you!
  market:
  brand: Edina Realty
  address: 14198 Commerce Avenue NE Ste 100 <br> Prior Lake, MN 55372
  phone: 952-212-3597
  phone_type:
  phone2:
  phone2_type:
  email: ChadandSara@edinarealty.com
  url: http://chadandsara.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.edinarealty.com/chad-and-sara-huebener-realtor/Selling/sell-a-home#/
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.edinarealty.com/chad-and-sara-huebener-realtor/listing/listingsearch#/properties?minPrice=0&maxPrice=0&nBed=0&nBath=0&pt_val=ForSale&age=age_any&sts_sale=1&sts_con=1&addl_stat=addl_stat_any&int_min_sqft=0&int_max_sqft=0&ext_min_sqft=0&ext_max_sqft=0&ext_gar=0&pgeSize=200&pgeNum=1&srtBy=DateListed'
  VR_form: http://oi.vresp.com?fid=3a54546ef4

sidebar_CTA:
  - CTA_image_path: /img/cta-images/005.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: 'https://www.edinarealty.com/chad-and-sara-huebener-realtor/listing/listingsearch#/properties?minPrice=0&maxPrice=0&nBed=0&nBath=0&pt_val=ForSale&age=age_any&sts_sale=1&sts_con=1&addl_stat=addl_stat_any&int_min_sqft=0&int_max_sqft=0&ext_min_sqft=0&ext_max_sqft=0&ext_gar=0&pgeSize=200&pgeNum=1&srtBy=DateListed'

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at Edina Realty is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/chadandsara/
  linkedin_url: https://www.linkedin.com/in/sarahuebener?trk=nav_responsive_tab_profile
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UC6kLoVcXcHlrm_J7n2hmeGg
  twitter_url: https://twitter.com/chadandsara
  instagram_url: https://www.instagram.com/chadandsara/
  pinterest_url: https://www.pinterest.com/ChadandSara
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/minnesota-real-estate-podcast-with-chad-and-sara-huebener/id1240303274?mt=2

podcast:
  title: Minnesota Real Estate Podcast With Chad and Sara Huebener 
  categories: Education
  image: http://i.imgur.com/c5A33wf.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Shakopee Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Edina Realty - your professional Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Shakopee, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Chad and Sara Huebener'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#E51937'
  theme_color: '#000000'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transperant

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
