audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Dr. Q & Dr. Ho
  license_number:
  about_markdown: |
   Many people meet doctors only after they've lost their health. Dr. Q has a purpose to educate as many families as possible towards optimal health and wellness through chiropractic and wellness lifestyle education, coaching and role-modeling. Ideally this would begin even before health is lost.
   Dr. Q's message is that you must eat, move and think right and be spiritually connected to express 100% of your God-given potential.  Health talks presented by Dr. Q describe living a wellness lifestyle -- eating right, moving right, and thinking right.  He has created and taught customized workouts to help improve the overall fitness level of his patients, with ages ranging from 12 to 90.
   <br><br>
   Through this experience Dr. Ho became a team leader not just for his staff, but also for his community.  He led his team and patients to better health through wellness lectures, group exercise classes, and most importantly through role modeling because he believe and practice what he preach.  He looks forward to bringing unique and advanced chiropractic care to the people of San Antonio.
   Dr. Ho's life purpose is to help people achieve a better quality of life.  He shares Pinnacle Wellness' vision to be the best health coach to as many families as possible and to bring this type of healthcare to the forefront of our healthcare system here in San Antonio.

  market:
  brand: Hacking Your Health
  brokerage: Presented by Pinnacle Wellness
  address: 4553 North Loop 1604 West Access Rd, Ste. 1107 San Antonio, TX 78249
  phone: 210-674-1234
  phone_type:
  phone2:
  phone2_type:
  email: hyh@pinnaclehealthchoice.com
  url: http://www.pinnaclehealthchoice.com

CTAs:
  first_CTA_text: Meet Us
  first_CTA_URL: http://pinnaclehealthchoice.com/meet-our-team.html?_ga=1.53080747.2099816095.1491592372
  second_CTA_text: Request Appoinment
  second_CTA_URL: https://my.chiromatrixbase.com/pinnaclehealthchoice.com/req-app.html
  VR_form: http://oi.vresp.com?fid=fa32913d36

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Visit Our Website
    CTA_text: See all of our services today!
    CTA_link_text: Wellness Awaits You
    CTA_url: https://pinnaclehealthchoice.chiromatrixbase.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at Hacking Your Health presented by Pinnacle Wellness is to be your best resource for valuable information, strategies, and tips on how to improve your health and your life.
    Chiropractic is the only health care system that works to maximize the natural, God-given strengths of the human body and its capacity to heal itself without the use of drugs or surgery.
    Subscribe to this blog to get the latest news on Chiropractic and receive expert tips for your experience and concerns.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Pinnwell?ref=ts
  linkedin_url:
  gplus_url: https://plus.google.com/100257215422913955297?gl=us&hl=en
  youtube_url: https://www.youtube.com/channel/UCx9r87_UHy9AVLCc7u0M18w
  twitter_url: https://twitter.com/Hack_YourHealth
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/hacking-your-health-podcast/id1234350825?mt=2

podcast:
  title: Hacking Your Health Podcast
  categories: Education
  image: /img/podcast.png
  subtitle: 'Find your best resource for valuable information, strategy and tips on how to improve your health and your life'
  description: 'If you are looking for your best resource for valuable information, strategy and tips on how to improve your health and your life -- get all the information and the latest updates from Dr. Q and Dr. Ho - the latest updates from Dr. Q and Dr. Ho'
  keywords: 'Chiropractic, Wellness, Exercise, General Health, Nutrition'
  author: 'Dr Q and Dr. Ho'

images:
  client_headshot_path: /img/headshots.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#008FC3'
  theme_color: '#008FC3'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#B5DA00'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#B5DA00'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
