audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Culture
    url: /culture/
  - title: Career Track
    url: /career/
  - title: Hiring FAQ's
    url: /hiring-process
  - title: Freebies + Events
    url: /freebies
  - title: Contact
    url: /contact
  # - title: Apply Now
  #   url: https://dave-friedman-team.breezy.hr/#positions

client:
  name: Dave Friedman
  license_number:
  about_markdown: |
    Being the No. 1 Realtor in families served annually and one of the top 2 two Realtors overall in Charleston for the last four years running, it is easy to say that Dave Friedman is committed to his work. Dave has proven that he has what it takes to help people buy or sell your home. He has closed well over 1,500 transactions in his 18+ years practicing real estate, earning countless raving fan reviews. He works hard to get his clients the deals they are looking for and averages 4% more savings for his clients than the average agent. Dave also sells 95% of his listings within 6six days, and within 99.5% of asking price, far exceeding the area average of 95%.

    Dave surrounds himself  and his team with the leading experts in the field and is committed to continuing their education so that he can always ensure they are offering the best advice and information for todayâ€™s market. Dave has hired a team of experts to work alongside him, from client care coordinators to closing experts, photographers, stagers to  and professional writers. He has built a team of successful, like-minded real estate professionals who are among some of the best in the business.


  market: Charleston
  brand: Dave Friedman Team
  brokerage: Keller Williams Realty
  address: 496 Bramson Ct Ste 200<br>Mt Pleasant, SC 29464
  phone: 843-800-2465
  phone_type:
  phone2:
  phone2_type:
  email: Dave@DaveFriedmanTeam.com
  url: http://www.ClickCharlestonSC.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808650';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: https://dave-friedman-team.breezy.hr/#positions
  second_CTA_text:
  second_CTA_URL:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how The Dave Friedman Team can take your business to new heights.
    CTA_link_text: Join Our Team
    CTA_url: /join-our-team

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: How to Sell More Homes
  welcome_text_markdown: >
    Whether you are just starting out, or you are licensed Broker, our team of professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/chsagentmastermind/
  linkedin_url: https://www.linkedin.com/company/dave-friedman-team/
  gplus_url: https://plus.google.com/+DaveFriedman?prsrc=5
  youtube_url: https://www.youtube.com/channel/UCYg5beOA0R1xWVZqukzSNBA
  twitter_url: https://twitter.com/RealEstateRants
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Dave-Friedman/
  trulia_url: http://www.trulia.com/profile/dave-friedman-agent-charleston-sc-9567361/overview
  yelp_url: http://www.yelp.com/biz/dave-friedman-real-estate-mount-pleasant
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: <br>
  hero_image_path: /img/background.jpg
  hero_background_hex: '#FFF'
  post_cover: /img/cover.jpg
  broker_logo: /img/kw.png

site_colors:
  brand_color: '#B40101'
  theme_color: '#4E4A46'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(61, 44, 50, .8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 20
  button_padding_height_number: 15
  button_border_color: '#B40101'
  button_background_color: '#B40101'
  button_text_color: '#fff'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
