audit_header: false
title: Central MS Real Estate Blog with Lee Garland
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808346';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
  form:

client:
  name: Lee Garland
  title:
  license_number:
  about_markdown: |
    We are excited about the fact that you are considering the Jackson Metro area of Mississippi. Lee Garland & The Moving On Team of RE/MAX Alliance are sure you will fall in love with one of our local communities where recreation and level 5 schools are abundant. Neighborhoods like Reunion, Buckingham and Bruenberg are just a sampling of what's out there. So if it's walking trails, water sports, golf or even an equestrian center you're looking for rest assured there is a place for you.

    If you are searching for an agent you will not have to look any further than Lee's team at RE/MAX Alliance. Just ask any of their clients and you will see there are no false promises, just years of experience backed by unbelievable guarantees. Such as the "Easy Exit Listing" allowing you to cancel your listing at anytime OR the "Love It Or Leave It" Home Buyers Advantage where they will resale your home for free during the first 3 years. There is also the "Guaranteed Sale" for sellers where Lee & Rita will buy your home if it does not sale.
  market: Central MS
  brand: The Moving On Team
  brokerage: RE/MAX Alliance
  address: 505 Avalon Way<br>Brandon, MS 39047
  phone: 601-983-1130
  phone_type:
  phone2:
  phone2_type:
  email: Lee@LeeGarland.com
  url: https://www.buy601.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://leegarland.freehousevalues.com/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.buy601.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://leegarland.freehousevalues.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.buy601.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/LeeGarlandMovingOn/
  linkedin_url: http://www.linkedin.com/in/theleegarland
  gplus_url: https://plus.google.com/u/0/114554364486440411847
  youtube_url: https://www.youtube.com/channel/UC8HYrc4nwuEBpwTf0WuZJlg
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/LeeGarland1/
  trulia_url:
  yelp_url: https://www.yelp.com/biz/lee-garland-re-max-alliance-brandon?osq=lee+garland
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Central MS Real Estate Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e11f26'
  theme_color: '#0a54a3'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
