audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1810160';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

client:
  name: Oggie Penev
  license_number:
  about_markdown: |
    Oggie Penev is the owner/broker of Realty Partners  and the team leader of Penev Realty Advisors in Phoenix Arizona. An active real estate broker licensed in Arizona, he deals with home sales on a daily basis. He has learned the nuances of what makes a seller or buyer truly successful. Oggie and his full service team have an incredible track record of proven success marketing and selling Phoenix Metro Area homes.

    The team consists of a listing department, buyer department, inside sales, and an administrative group that includes marketing, listing and transaction management. Oggie has an associate degree in Business and Finance. He was Rookie of the year in his first year in the business, and has sold nearly 100 million to-date.  Currently Oggie is ranked in the TOP 1% in the Phoenix market.
  market: Phoenix
  brand: Penev Realty Advisors
  brokerage:
  address: 8755 E Bell Rd. 107 <br> Scottsdale, AZ 85260
  phone: 602-362-8828
  phone_type:
  phone2:
  phone2_type:
  email: oggiepenev@penevrealtyadvisors.com
  url: http://www.PenevRealtyAdvisors.net

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://penevrealtyadvisors.net/sell/what-is-my-home-worth
  second_CTA_text: Home Search
  second_CTA_URL: http://penevrealtyadvisors.net

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://penevrealtyadvisors.net/sell/what-is-my-home-worth

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://penevrealtyadvisors.net

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/PenevRealtyAdvisors/
  linkedin_url: https://www.linkedin.com/in/oggiepenev/
  gplus_url: https://plus.google.com/113453365547659203749
  youtube_url: https://www.youtube.com/channel/UCPTTArpy0vyHmvbyOTFO0WQ
  twitter_url: https://twitter.com/PenevRealty
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Oggie-Penev/
  trulia_url: 
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 65
  hero_text: -- MARKET -- Real Estate Video Blog<br>Buy, Sell, Invest
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#EE7108'
  theme_color: '#29222A'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
