audit_header: false
title: Mississippi Gulf Coast Real Estate Video Blog with Bryan David
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Contact
    url: http://www.coasthomesales.com/member/contact/
client:
  name: Bryan David
  title: Broker Associate
  license_number:
  about_markdown: 'Bryan is a Top Producing MS state licensed Broker and practices real estate as a Broker Associate at Keller Williams of South Mississippi. His team, the Bryan David Group, provides 5-star residential real estate services across the MS Gulf Coast. He is a member in good standing of the Gulf Coast, the Mississippi, and the National Associations of Realtors&reg;.'
  market: Mississippi Gulf Coast
  brand: Bryan David Group
  brokerage: Keller Williams Realty
  address: '6819 Washington Ave, Suite F<br>Ocean Springs, MS 39564'
  phone: (228) 215-1861
  phone_type:
  phone2:
  phone2_type:
  email: Bryan@BDGRealEstate.com
  url: 'http://coasthomesearch.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.coasthomesales.com/cma/property-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.coasthomesales.com/'
  VR_form: 'http://oi.vresp.com?fid=ee203e8ab4'
sidebar_CTA:
  CTA_image_path: /img/cta-images/003.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: 'http://www.coasthomesales.com/'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/bryandavidgroup/'
  linkedin_url: 'https://www.linkedin.com/in/bryandavidgroup'
  gplus_url: 'https://plus.google.com/u/0/b/102286159213022737030'
  youtube_url: 'https://www.youtube.com/channel/UC6A9ObAfV1rnMnNOkJrh6wA'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/bryan-david/'
  trulia_url: 'https://www.trulia.com/profile/bryan-david-agent-ocean-springs-ms-zgvyhmng/overview'
  yelp_url: 'https://www.yelp.com/biz/bryan-david-group-ocean-springs'
  podcast_url: 'https://itunes.apple.com/us/podcast/mississippi-gulf-coast-real-estate-podcast-bryan-david/id1211755092?mt=2'
podcast:
  title: Mississippi Gulf Coast Real Estate Podcast with Bryan David
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/bdglogo.png
  logo_width_number: 40
  hero_text: Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#192f5b'
  theme_color: '#4b4d4e'
  theme_text_color: '#ffffff'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 0px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'