audit_header: false
title: -- CLIENT BRAND --
description: A Video Blog about -- MARKET -- Real Estate; It's industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
show_custom_links: true
custom_links:
  - title: We Recommend
    url: /vendors/
  - title: Testimonials
    url: /client-testimonials/
  - title: Our Agents
    url: /our-agents/
  - title: Morning Huddles
    url: /morning-huddles/

client:
  name: Adrienne Lally & Attilio Leonardi
  license_number: '#RB - 21303'
  about_markdown: |
    Team Lally is currently ranked in the Top 5 Real Estate Team in the State of Hawaii for Sales & Volume! Adrienne Lally, President of Team Lally has been awarded 7-time consecutive years place in Hawaii Business Top 100 Realtors in Hawaii. We have led our team in selling over 100+ homes per year in Hawaii for multiple years. In 2016 we closed out the year with 171 closed transactions and 82 million in sales.
  market: Honolulu
  brand: Team Lally
  brokerage: Keller Williams Honolulu
  address: '1001 Kamokila Blvd #106 <br> Kapolei, HI 96707'
  phone: (808) 212-9188
  phone_type:
  phone2:
  phone2_type:
  email: info@teamlally.com
  url: https://www.teamlally.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808309';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Real Estate Careers
  first_CTA_URL: https://www.teamlally.com/careers.php
  # second_CTA_text: Apply
  # second_CTA_URL: /apply/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Start your path to a career in real estate. Real estate careers are available in Honolulu, Oahu, Maui, Kauai, and Big Island.
    CTA_link_text: Learn More
    CTA_url: https://www.teamlally.com/careers.php

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: How to Sell More Homes
  welcome_text_markdown: >
    Whether you are just starting out, or you are licensed Broker, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TeamLallyHawaii
  linkedin_url: https://www.linkedin.com/in/adriennelally
  gplus_url: https://plus.google.com/+AdrienneLallyandteamlally/posts
  youtube_url: https://www.youtube.com/user/adriennelally
  twitter_url: https://twitter.com/TeamLally
  instagram_url: https://www.instagram.com/teamlally_hawaii/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Team-Lally/
  trulia_url: http://www.trulia.com/profile/team-lally-broker-kapolei-hi-843530/
  yelp_url: https://www.yelp.com/biz/team-lally-kapolei-2
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Boost your Career with Veteran Real Estate Agent -- CLIENT NAME --'
  description: A Podcast about -- MARKET -- Real Estate; It's industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
  keywords: '-- MARKET -- Real Estate, Real Estate Careers, Real Estate Professionals, Realtors, Real estate industry, how much do realtors make'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  client_headshot2_path: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: Real Estate Careers and Training Video Blog
  hero_background_hex: '#91CEC6'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#b40101'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 3
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
