audit_header: false
title: "Florida's Emerald Coast Real Estate Video Blog with Nathan Abbott"
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  # - title: Venue Reviews
  #   url: /venuereviews.html
  - title: Testimonials
    url: http://nathanabbottteam.com/testimonials/
  - title: Online Reviews
    url: http://nathanabbottteam.com/online-reviews/

client:
  name: Nathan Abbott
  license_number:
  about_markdown: |
    The name Abbott is synonymous with real estate along Florida’s Emerald Coast. The Abbott’s have been making real estate their business since 1950 starting with the original Abbott Realtor, William W. Abbott Sr.

    Steve and Bill Abbott followed in their father’s footsteps and founded Abbott Realty in 1977 with a $3,000 investment. Combined with an unsurpassed work ethic, this small monetary investment created a multimillion-dollar-a-year company, employing more than 1,000 people and becoming the largest employer in NW Florida since the mid 80s. The Abbott’s were involved with the most premier real estate properties along the Emerald Coast.

    The Nathan Abbott Team are natives to the area and keep the business in the family by becoming the third generation of Abbott Realtors. Although times have definitely changed since the inception of the business, its founding principles have remained the same... customer service, knowledge, hard work and dedication.
  market: "Florida's Emerald Coast"
  brand: Nathan Abbott Team
  brokerage: Resort Quest Real Estate
  address: 9657 Hwy. 98. W<br>Miramar Beach, FL 32550
  phone: 850-632-0136
  phone_type:
  phone2:
  phone2_type:
  email: Nathan@NathanAbbottTeam.com
  url: http://www.NathanAbbottTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://nathanabbottteam.com/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.finddestinrealestate.com/search/map?baths=1&beds=1&haslat=1&haslong=1&listingtype=Condo&listingtype=Single%20Family&minprice=200000&page=1&perpage=50&soldproperty=0&sortby=latest&type=map
  phone_CTA: true
  VR_form: http://oi.vresp.com?fid=72c973d97f

sidebar_CTA:
  CTA_image_path: /img/CTA1.jpg
  CTA_title: Looking to Sell a Home?
  CTA_text: "The Nathan Abbott Team is here to guide you and be your trusted real estate advisor."
  CTA_link_text: Home Valuation
  CTA_url: http://nathanabbottteam.com/property-valuation/

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for NW Florida's Emerald Coast. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/NathanAbbottTeam/?ref=hl
  linkedin_url: https://www.linkedin.com/in/nathan-abbott-04264111
  gplus_url: https://plus.google.com/106408544805273531883
  youtube_url: https://www.youtube.com/channel/UC1y00cFB4V9xULUkZMt5eSA
  twitter_url: https://twitter.com/nabbott36
  instagram_url: https://www.instagram.com/nathanabbottteam/
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Nathan-Abbott-Team/
  trulia_url: https://www.trulia.com/profile/nathan-abbott-agent-miramar-beach-fl-zgd65rtl/overview
  yelp_url: https://www.yelp.com/biz/nathan-abbott-team-resortquest-real-estate-miramar-beach
  podcast_url: https://itunes.apple.com/us/podcast/floridas-emerald-coast-real/id1192495106?mt=2

podcast:
  title: "Florida's Emerald Coast Real Estate Podcast with Nathan Abbott"
  categories: News &amp; Politics
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60rem
  hero_text:
  hero_background_hex: '#09A5E4'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#09A5E4'
  theme_color: '#09A5E4'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 3px
  shadow_color: "#B2C9CA"

buttons:
  button_radius_number: 0px
  button_padding_width_number: 10px
  button_padding_height_number: 15px
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#09A5E4'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
