audit_header: false
title: CORE Real Estate Training
description: A Video Blog about -- MARKET -- Real Estate; its industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
show_custom_links: true
custom_links:
  - title: Events
    url: /


emma:
  lightbox:
  form:

client:
  name: Patrick O'Sullivan
  designation: CCIM
  title: Designated Broker | Owner
  license_number:
  about_markdown: |
    I am the Broker/Owner for Cap Core Real Estate and we specialize in adding value to the lives of our clients thru residential and multifamily real estate. Last year was our best year since the company was founded both in transaction count and revenue.
  market: Phoenix
  brand: Cap CORE Real Estate
  brokerage:
  address: 4320 East Milky Way<br>Gilbert, AZ 85295
  phone: 602-366-5078
  phone_type:
  phone2:
  phone2_type:
  email: Patrick@CapCoreRealEstate.com
  url: http://CapCoreRealEstate.com

CTAs:
  first_CTA_text: Join Our Team
  first_CTA_URL: /join-our-team/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how we can take your business to new heights.
    CTA_link_text: Join Our Team
    CTA_url: /join-our-team/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/AZRealEstateInvesting/
  linkedin_url: https://www.linkedin.com/company/cap-core-real-estate
  gplus_url: https://plus.google.com/+CapCoreRealEstateTempe
  youtube_url: https://www.youtube.com/channel/UCQnXVWhQ7FG8RjQyLtjlyHg
  twitter_url: https://twitter.com/getAZrealestate
  instagram_url:
  pinterest_url:
  # zillow_url: https://www.zillow.com/profile/getAZrealestate/
  # trulia_url: https://www.trulia.com/profile/patrick-o-sullivan-agent-gilbert-az-zglv18x2/overview
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Careers and Training Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: Boost Your Career with Veteran Agent {{site.data.settings.client.name}}
  description: A Podcast about -- MARKET -- Real Estate; It's industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
  keywords: -- MARKET -- Real Estate, Real Estate Careers, Real Estate Professionals, Realtors, Real estate industry, how much do realtors make
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: -- MARKET -- Real Estate Coaching Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#8A2529'
  theme_color: '#6A747C'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0, 0, 0, .75)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
