audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Radio Show
    url: /radio-show/
  - title: Careers
    url: http://realestatecareersinpalmbeach.blogspot.com/
  - title: Divorce and Real Estate
    url: https://goo.gl/forms/GL4oqvSlUOsfB7WT2
client:
  name: Lisa Treu
  license_number:
  about_markdown: |
    Lisa Treu knows that creating opportunities is what she loves to do each day. Selling Real estate is more than selling a house, it is someone's home and each closing is treated with care.  In 2014, Treu Group Real Estate was honored to earn the endorsement of Real Estate Mogul and member of Shark Tank, Barbara Corcoran. Additionally, due to our innovative marketing, we were the only local real estate company or agent nominated as the 2014 and 2015 Top Real Estate marketer in North America. Lisa is honored to bring current real estate information each week on WJNO. Lisa is here to help Treu Group Real Estate clients get to the closing table.  Lisa understands luxury real estate, marketing, negotiating, and studies the market to help our clients get ahead of changes that are always happening in Palm Beach and Martin County.
  market:
  brand: The Treu Group
  brokerage: Treu Group Real Estate
  address: Palm Beach & Martin County, FL
  phone: 561-352-3056
  phone_type:
  phone2:
  phone2_type:
  email: lisa@treugroup.com
  url: http://www.treugroup.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809172';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://whatsmypalmbeachcountyhomevalue.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.treugroup.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://whatsmypalmbeachcountyhomevalue.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.treugroup.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/treugrouprealestate/?fref=ts
  linkedin_url: http://www.linkedin.com/in/treugroup
  gplus_url: https://plus.google.com/+LisaTreu
  youtube_url: https://www.youtube.com/channel/UCZ113PqNjQbuegjfueaTvmA
  twitter_url: https://twitter.com/LisaTreu
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Treu-Group/
  trulia_url: http://www.trulia.com/profile/treugroup/
  yelp_url: http://www.yelp.com/biz/treu-group-real-estate-delray-beach?nb=1
  podcast_url: https://itunes.apple.com/us/podcast/treu-group-real-estate-weekly-tips/id891067870?mt=2

podcast:
  title: Palm Beach Real Estate Podcast with The Treu Group
  categories: Education
  image: http://i.imgur.com/9KV2FyM.jpg
  subtitle: 'Real Estate Tips and Tricks for the Palm Beach and Martin County market'
  description: "I'll update you with how to make a smart decision in real estate, improve the value of your home, and keep you up to date on what's happening in our local Palm Beach & Martin County real estate market."
  keywords: 'Real,Estate,Palm,Beach,Market,Sale,Lisa,Treu,Group,Tips,Tricks,South,Florida,agents,educational,informative,housing,house,short,talk,show,radio,martin,county'
  author: 'The Treu Group'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#24a8b6'
  theme_color: '#e32735'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0,63,76,.8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
