audit_header: false
title: Louisville Real Estate Video Blog with Bob Sokoler
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Our Raving Fans
    url: /raving-fans

client:
  name: Bob Sokoler
  license_number:
  about_markdown: |
    Bob Sokoler is the owner of The Sokoler Medley Team at RE/MAX Properties East in Louisville, Kentucky, which has ranked No. 1 in the city for sales volume Six years in a row! His team sold more than 404 homes in 2016 and more than 340 properties in 2015.

    Before becoming a realtor in 2004, Bob was a two-time Emmy Award-winning journalist, serving as the anchor and reporter for WHAS TV and the television show “Louisville Tonight Live.” Prior to that, he was also the anchor and a reporter for the 5:00pm News at WXIA-TV in Atlanta, Georgia; the weekend news anchor and a field reporter for the 5:30pm news at WCPX-TV in Orlando, Florida; and a news reporter at a number of other highly regarded stations – including WJZ-TV in Baltimore, KUTV-TV in Salt Lake City, and WYRT-TV in Flint, Michigan.
  market: Louisville
  brand: The Sokoler Medley Team
  brokerage: RE/MAX Properties East
  address: 10 525 Timber Wood Cir. Louisville, KY 40223
  phone: 502-376-5483
  phone_type:
  phone2:
  phone2_type:
  email: Bob@WeSellLouisville.com
  url: http://www.weselllouisville.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.weselllouisville.com/sell/track-your-homes-value/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.weselllouisville.com/property-search/search-form/
  VR_form: http://oi.vresp.com?fid=ad2cd4ec14

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://www.weselllouisville.com/sell/track-your-homes-value/

second_sidebar_CTA:
  - CTA_image_path2: /img/truck.jpg
    CTA_title2: "Moving?"
    CTA_text2: "Buy or sell with The Sokoler and Medley Team and use our moving truck for free."
    CTA_link_text2: "Use Our Truck"
    CTA_url2: http://www.welistlouisville.com/use_our_moving_truck

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Louisville-Real-Estate-with-the-Sokoler-Medley-Team/244168452281132
  linkedin_url: https://www.linkedin.com/pub/bob-sokoler/9/6a5/507
  gplus_url: https://plus.google.com/u/0/+LouisvilleHomes/
  youtube_url: https://www.youtube.com/channel/UC2O5BoAYEtc5RzhWHUv8bEQ
  twitter_url: https://twitter.com/BobSokoler
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/bobsokoler/
  trulia_url: http://www.trulia.com/profile/bobsokoler/
  yelp_url: http://www.yelp.com/biz/the-medley-sokoler-team-louisville?nb=1
  podcast_url: https://itunes.apple.com/us/podcast/bob-sokoler/id1263653061

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 100
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#033977'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(238, 238, 238, .7)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
