audit_header: false
title: Phoenix and Scottsdale Real Estate Show with Kelly Cook
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Communities
    url: http://azhomesbykellycook.com/phoenix-cities-and-communities/
  - title: About
    url: http://azhomesbykellycook.com/home/about-us/
  - title: Testimonials
    url: http://azhomesbykellycook.com/home/about-us/client-testimonials/
  - title: Meet Our Team
    url: /meet-our-team/
emma:
  lightbox:
  form:

client:
  name: Kelly Cook
  title:
  license_number:
  about_markdown: |
    Kelly’s personal experience as a student athlete & collegiate football coach has provided valuable insight and experience that propelled him in the real estate industry. As a student-athlete, Kelly played football at the University of Nebraska, participating on the offensive side of the ball at both Quarterback and Wide Receiver. During his tenure at the University of Nebraska, Kelly competed in two BCS Bowls, one Conference Championship game, and one National Championship game. After the conclusion of his football playing career and graduation from the University of Nebraska, Kelly served on the coaching staff at Nebraska and Ole Miss.

    In 2005, Kelly decided to take the skill set he acquired competing in collegiate athletics and apply it to the real estate industry here in Arizona. Leadership, integrity, and work ethic are the core competencies of Kelly Cook and the Kelly Cook Real Estate Group. These simple, yet profound intangibles have turned Kelly Cook Real Estate Group into one of the largest and successful Short Sale Teams in Arizona. If you are looking for a real estate agent that enjoys the challenge of negotiating with your bank, then you have arrived at the correct place. Kelly has helped hundreds of homeowners successfully short sale their homes and help set them up with a game plan moving forward to ensure they are able to purchase another home just as soon as they are eligible. Whatever your end goals are, we can help you fulfill that exit strategy and will do whatever it takes to make sure you become a satisfied client for life!
  market: Phoenix and Scottsdale
  brand: Kelly Cook Real Estate Group
  brokerage: Keller Williams
  address: 15333 N Pima Rd<br>Scottsdale, AZ 85260
  phone: 480-227-2028
  phone_type:
  phone2:
  phone2_type:
  email: kelly@kellycookhomes.com
  url: http://kellycookhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.phoenixazrealestatesource.com/?utm_source=Vyral%20Marketing&utm_medium=Vyral%20Call%20to%20Action%20Button&utm_campaign=Free%20Home%20Value%20Report%20Button
  second_CTA_text: Home Search
  second_CTA_URL: https://www.arizonarealestatesource.com/?utm_source=VYRAL&utm_campaign=KellyCookHomes:SearchHomesLink&utm_medium=referral

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.phoenixazrealestatesource.com/?utm_source=Vyral%20Marketing&utm_medium=Vyral%20Call%20to%20Action%20Button&utm_campaign=Free%20Home%20Value%20Report%20Button

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.arizonarealestatesource.com/?utm_source=VYRAL&utm_campaign=KellyCookHomes:SearchHomesLink&utm_medium=referral

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KellyCookRealEstateGroup
  linkedin_url: https://www.linkedin.com/in/cookkelly
  gplus_url: https://plus.google.com/+KellyCookRealEstateGroupScottsdale/posts
  youtube_url: https://www.youtube.com/channel/UCWxi4GOOcdFF7XTrDsSY-AA
  twitter_url: https://twitter.com/KCREGroup
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/KCRealEstateGroup/
  trulia_url: http://www.trulia.com/profile/kelly-cook-real-estate-group-agent-scottsdale-az-zgsmbbgr/overview
  yelp_url: http://www.yelp.com/biz/kelly-cook-real-estate-group-scottsdale
  podcast_url: https://itunes.apple.com/us/podcast/greater-phoenix-real-estate/id1106098255

podcast:
  title: Phoenix and Scottsdale Real Estate Show with Kelly Cook
  categories: Education
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: Phoenix and Scottsdale Real Estate Show
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgb(72, 67, 87)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
