audit_header: false
title: '-- CLIENT BRAND --'
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
  -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Gregory & Kimberli Taylor
  license_number:
  about_markdown: >
    Greg & Kim are dedicated professionals whose diligence and marketing savvy
    provide the best formula for continued success. Their determination to cater
    to clients specific needs, attention to detail and sharp negotiating skills
    allows them to receive first class service with utmost integrity. Whether
    it's a person looking for their first home or a company looking to do a
    condo conversion, Team Taylor Real Estate Group has the expertise and
    experience to get the job done. Their goal is to exceed your expectations.
    Their warm, sincere yet professional business style will turn you into a
    client for life.
  market: New Jersey
  brand: Team Taylor Real Estate Group
  brokerage: Liberty Realty
  address: '131 Washington St <br> Hoboken, NJ 07030'
  phone: 917-805-5411
  phone_type: Greg
  phone2: 201-920-2604
  phone2_type: Kimberli
  email: Greg@TeamTaylorInc.com
  email2: Kim@TeamTaylorInc.com
  url: 'http://www.HudsonCountyHomes.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.hudsoncountyhomes.com/cma/property-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: >-
    http://www.hudsoncountyhomes.com/map_search/results/5/1/#/?city=all&baths_min=all&beds_min=all&area_min=all&list_price_max=all&type=res&type=con&list_price_min=50000&building_name=all&page=1&per_page=20

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809079';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /uploads/unnamed-6.jpg
    CTA_title: Whatâ€™s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: 'http://www.hudsoncountyhomes.com/cma/property-valuation/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: >-
      http://www.hudsoncountyhomes.com/map_search/results/5/1/#/?city=all&baths_min=all&beds_min=all&area_min=all&list_price_max=all&type=res&type=con&list_price_min=50000&building_name=all&page=1&per_page=20
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/TeamTaylorInc'
  linkedin_url: 'http://www.linkedin.com/in/gregorytaylor1'
  gplus_url: 'https://plus.google.com/104476232098673560804/posts?hl=en'
  youtube_url: 'https://www.youtube.com/channel/UC4nDVyzOD9oH8bPS3C--WZA'
  twitter_url: 'https://twitter.com/teamtaylorinc'
  instagram_url: 'https://www.instagram.com/teamtaylortv/?hl=en'
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/MrGregoryTaylor/'
  trulia_url: >-
    https://www.trulia.com/profile/greg-kim-taylor-agent-hoboken-nj-zgxnwg1g/overview
  yelp_url: 'https://www.yelp.com/biz/team-taylor-real-estate-group-hoboken'
  podcast_url:
podcast:
  title:
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#192d50'
  theme_color: '#192d50'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(238, 238, 238, 0.5)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'