audit_header: false
title: -- CLIENT BRAND --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: John Hatch
  license_number:
  about_markdown: At the Hatch Homes Group, your needs are the top priority. John has been living in the Portland area since 1992 and his team is composed of people that have lived in the area their whole lives. He has prestigious CRS accreditation and is also a member of the Real Estate Buyers Agent Council and has earned the Accredited Buyer's Representative (ABR) designation. John and his wife Melody know that buying or selling a home is one of the most important transactions you make, and want to help make that experience as smooth and rewarding as possible.

  market: Portland
  brand: Hatch Homes Group
  brokerage: Keller Williams Realty Professionals
  address: 9755 SW Barnes Rd., Ste 560<br> Portland, OR 97225
  phone: (503) 974-4104
  phone_type: Office
  phone2: (503) 748-8360
  phone2_type: Fax
  email: john@hatchhomes.com
  url: http://www.hatchhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.hatchhomes.com/Sell/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.hatchhomes.com/results-gallery/?sort=popularity&status=A
  VR_form: http://oi.vresp.com?fid=cf9a7aa11d

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: https://www.hatchhomes.com/Sell/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.hatchhomes.com/results-gallery/?sort=popularity&status=A

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/hatchhomes/
  linkedin_url: https://www.linkedin.com/in/hatchhomes
  gplus_url: https://plus.google.com/116790347874656754917/
  youtube_url: https://www.youtube.com/channel/UCmooPuwXb8578KmxOgU_NtA
  twitter_url: https://twitter.com/hatchhomesgroup
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Hatch-Homes-Group/
  trulia_url: http://www.trulia.com/profile/hatchhomesgroup/
  yelp_url: http://www.yelp.com/biz/hatch-home-group-portland?nb=1
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
