audit_header: false
title: Las Vegas Real Estate Video Blog with Mike Chobanian
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Buy A Home
    url: http://www.vegascapital.com/buy-a-home/
  - title: Sell A Home
    url: http://www.vegascapital.com/free-home-value/

client:
  name: Mike Misak Chobanian
  license_number:
  about_markdown: |
    Mike Chobanian & Vegas Capital Realty is a full service real estate and property management company, specializing in Selling, buying and property management. We provide expert advice that specializes in the local Las Vegas, Henderson Market. We offer excellent customer service while offering our clients the latest in cutting edge technology in order to gain maximum listing exposure to sell your house and buying the perfect home along with managing your rental property to maximize your profit.

    Let Mike Chobanian & Vegas Capital Realty help you buy, sell, invest or property management today!
  market: Las Vegas
  brand: Vegas Capital Realty
  brokerage:
  address: '8860 S Maryland Pkwy Suite #123<br>Las Vegas, NV 89123'
  phone: 702-666-8688
  phone_type:
  phone2:
  phone2_type:
  email: info@VegasCapital.com
  url: http://www.VegasCapital.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809198';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.vegascapital.com/index.php/free-home-value/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.vegascapital.com/index.php/homes-for-sale-search-advanced/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.vegascapital.com/index.php/free-home-value/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.vegascapital.com/index.php/homes-for-sale-search-advanced/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  brand: Lender Co.
  license_number2:
  phone:
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: http://www.facebook.com/VEGASCAPITALREALTY
  linkedin_url: https://www.linkedin.com/in/mike-misak-tchobanian-77a40218
  gplus_url: https://plus.google.com/115451540181467711631
  youtube_url: https://www.youtube.com/channel/UCa_qhCRZiSJMxl82mbAs0-w
  twitter_url: https://twitter.com/vegascapital
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Mike-Tchobanian/
  trulia_url: http://www.trulia.com/profile/mike-Chobanian-agent-henderson-nv-zgsxlckd/overview
  yelp_url: http://www.yelp.com/biz/vegas-capital-realty-henderson
  podcast_url: https://itunes.apple.com/us/podcast/feedburner-vegas-capital-realty/id1199532177?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#231f20'
  theme_color: '#424342'
  accent_color: '#fec62e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#231f20'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
