audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /client-testimonials
  - title: Book an Appointment with Jonathan
    url: http://calendly.com/jonathan-carbutti

client:
  name: Jonathan Carbutti
  license_number:
  about_markdown: |
    Jonathan defines himself as an educator first, and real estate broker second. He enjoys educating the consumer, Buyers and Sellers alike, and dispelling many of the “myths” of buying and selling. As a successful real estate investor as well Jonathan is able to offer practical and useful advice whether you are the first-time investor or seasoned pro.
  market: New Haven & Fairfield County
  brand: Carbutti & Co Realtors
  brokerage:
  address: 72 South Main Street<br>Wallingford, CT 06492
  phone: 203-980-6886
  phone_type:
  phone2:
  phone2_type:
  email: Jonathan.Carbutti@gmail.com
  url: https://www.CarbuttiRealEstate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.carbuttirealestate.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.carbuttirealestate.com/
  VR_form: http://oi.vresp.com?fid=bb38540c56

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.carbuttirealestate.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.carbuttirealestate.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/carbuttirealtors
  linkedin_url: https://www.linkedin.com/in/jonathancarbutti
  gplus_url: https://plus.google.com/u/0/106419527654513649170/posts
  youtube_url: https://www.youtube.com/channel/UCiKVxtj6Si3d6fCxp1Vag2w
  twitter_url: https://twitter.com/CarbuttiBlog
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url: http://www.yelp.com/biz/carbutti-and-co-realtors-wallingford-2
  podcast_url: https://itunes.apple.com/us/podcast/new-haven-fairfield-county/id1178093104?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0070ab'
  theme_color: '#b0b7bc'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(250, 250, 250, .4)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
