audit_header: false
title: Valencia Real Estate Video Blog with Randy Plaice
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name:
  license_number: "CalBRE #01863252"
  about_markdown: |
    'With so many Realtors out there eager for your business, what do I provide that makes me any different? Team Approach: They say "A Team Always Outperforms An Individual." The reason is simple: The business of Real Estate is a complex and broad area and you as the client deserve to be served by agents and brokers who are super specialized in the areas that matter to you.'
  market: Valencia
  brand: Randy Plaice &amp; Associates
  brokerage: Re/Max of Valencia
  address: 27720 Dickason Drive<br>Valencia, CA 91355
  phone: 661-702-4626
  phone_type: Office
  phone2: 818-294-0414
  phone2_type: Cell
  email: salesteam@randyplaice.com
  url: http://www.randyplaiceandassociates.com

CTAs:
  first_CTA_text: Home Evaluation
  first_CTA_URL: http://randyplaice.com/sellers
  second_CTA_text: Home Search
  second_CTA_URL: http://randyplaice.com/search
  phone_CTA: true
  VR_form: http://oi.vresp.com?fid=f02f63ee72

sidebar_CTA:
  CTA_image_path: /img/cta-images/005.jpg
  CTA_title: Looking to Sell a Home?
  CTA_text: "Get Your Home's Value"
  CTA_link_text:
  CTA_url:

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/RandyPlaiceandAssociates?ref=br_rs
  linkedin_url: https://www.linkedin.com/in/randyplaicevalenciarealestate
  gplus_url: https://plus.google.com/+RandyplaiceandAssociates
  youtube_url: https://www.youtube.com/user/RandyPlaiceRealtor
  twitter_url: https://twitter.com/randyplaice
  instagram_url:
  pinterest_url: https://www.pinterest.com/randyplaice/
  zillow_url: http://www.zillow.com/profile/Randy-Plaice/
  trulia_url: https://www.trulia.com/profile/randy-plaice-agent-valencia-ca-zgkp29j7/overview
  yelp_url: https://www.yelp.com/biz/randy-plaice-and-associates-re-max-of-valencia-valencia
  podcast_url: https://itunes.apple.com/us/podcast/valencia-real-estate-video/id1195140360?mt=2

podcast:
  title: Valencia Real Estate Video Blog with Randy Plaice
  categories: News &amp; Politics
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Randy Plaice'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60rem
  hero_text: Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#04BCA8'
  theme_color: '#374E59'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0px
  button_padding_width_number: 10px
  button_padding_height_number: 15px
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#374E59'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
