audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Testimonials
    url: http://www.nateshomes.com/Client-Reviews

client:
  name: Nate Martinez
  license_number:
  about_markdown: |
    Nate has been selling real estate in the Valley of the Sun for nearly thirty years. He is the co-owner of RE/MAX Professionals, founded in 2001 and has six valley locations in Glendale, Surprise, Anthem, Arrowhead Ranch, Avondale, and Sun City West.

    Nate believes in education and giving back to the real estate industry. His designations include ABR, CRS, GRI, CDPE, CIAS, CLHS, CRP, e-PRO and SFR Each year, Nate attends numerous seminars and training events across the country. As a guest speaker, Nate has been able to train hundreds of real estate professionals, while also learning from some of the best agents in the industry.

    When he is not working, Nate enjoys spending time with his fiance, Tonya, his two daughters, Brandi and Mila and his son Nathan Jr. He is an avid sports enthusiastic, loves attending concerts and practicing his golf swing. Nate's personal philosophy is a quote from the great Wayne Gretsky, "skate to where the puck is going, not where its been!"
  market: Glendale
  brand: RE/MAX Professionals
  brokerage:
  address: 7111 W. Bell Rd. Suite 101<br>Glendale, AZ 85308
  phone: 602-942-7000
  phone_type:
  phone2:
  phone2_type:
  email: info@NatesHomes.com
  url: http://nateshomes.com/

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.natemartinezteam.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.natemartinezteam.com/
  VR_form: http://oi.vresp.com?fid=39d9e3ccea

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: http://www.natemartinezteam.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/NateMartinezTeam/
  linkedin_url: http://www.linkedin.com/in/natemartinez
  gplus_url: https://plus.google.com/110224445429180454577
  youtube_url: https://www.youtube.com/user/natemartinez8
  twitter_url: http://twitter.com/NateMartinez
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Nate-Martinez/
  trulia_url: https://www.trulia.com/profile/nate-martinez-agent-glendale-az-zgwmjqkx/overview
  yelp_url: https://www.yelp.com/biz/nate-martinez-re-max-professionals-glendale-2
  podcast_url:

podcast:
  title: Glendale Real Estate Podcast with Nate Martinez
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#e11b22'
  theme_color: '#0054a4'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#e11b22'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
