audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox:
  form:

client:
  name: Willie Miranda
  title:
  license_number:
  about_markdown: |
    Willie Miranda began his real estate career in the Capital Region in 1998 with Coldwell Banker. He left there and went to work for RE/MAX Premier until 2002, at which time he decided to go out on his own and established Miranda Real Estate Group, Inc. in July of 2002.

    This decision was made by Willie’s desire and vision “To help the best agents in our region build a business while making it hassle-free to our clients.” His innovative and progressive approach to real estate has been the driving force behind the continued expansion and success of his unique "Sales Team Systems.”
    
    Willie is a Certified Trainer of the Brian Buffini "100 Days To Greatness" and "Peak Producers" program. He is also a member of an elite group of the Top Realtors in the Country and a Master Trainer and Coach for the Craig Proctor "Quantum Leap System". Miranda Real Estate Group, Inc. has won the Albany Business Reviews "Best Places To Work" Award multiple times over the past few years. Willie was also a recipient of the Business Reviews 2006, “40 Under Forty" award.
  market:
  brand:
  brokerage:
  address: 1482 Route 9, Clifton Park, NY 12065
  phone: 518-376-1073
  phone_type:
  phone2:
  phone2_type:
  email: wmiranda@mrgteam.com
  url: http://williemiranda.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.518homevalue.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.williemiranda.com/VIP_buyer.asp

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/mirandarealestategroup
  linkedin_url: https://www.linkedin.com/in/williemiranda
  gplus_url: https://plus.google.com/106883494246867860601
  youtube_url: https://www.youtube.com/user/wmj2517
  twitter_url: http://www.twitter.com/WillieMiranda
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/WillieMirandaRE/
  trulia_url: http://www.trulia.com/profile/willie-miranda-agent-clifton-park-ny-8656583
  yelp_url: http://www.yelp.com/biz/miranda-real-estate-group-saratoga
  podcast_url: https://itunes.apple.com/us/podcast/willie-miranda-home-selling/id1093143928?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#005189'
  theme_color: '#030D14'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
