audit_header: false
title: Quarterback to Coach Podcast
description: 'Jerimiah Taylor and Isacc Guzman swap their secrets on how to polish your leadership skills, shift your business mindset, and empower your team.'
show_custom_links: true
custom_links:
  - title: Resources
    url: https://www.linkedin.com/company/quarterback-to-coach

client:
  name:
  license_number:
  about_markdown: |

  market:
  brand: Quarterback to Coach
  brokerage:
  address:
  phone:
  phone_type:
  phone2:
  phone2_type:
  email:
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
  VR_form:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.png
    CTA_title: "GET IT FREE: The Millionaire Real Estate Agent Book"
    CTA_text: "Let's visit about how to help you be more successful at your San Diego real estate career. When we meet you'll get a free copy of the best-selling book The Millionaire Real Estate Agent: It's Not About the Money...It's About Being the Best You Can Be! Absolutely no-obligation. It's yours to keep."
    CTA_link_text: "Contact Me"
    CTA_url: /contact/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: The place where entrepreneurs come to become leaders.
  welcome_text_markdown: >
    Jerimiah Taylor and Isacc Guzman swap their secrets on how to polish your leadership skills, shift your business mindset, and empower your team. Subscribe to this blog to get the latest tips and tricks to help you be a successful entrepreneur.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Quarterback-to-Coach-1368265103218754/
  linkedin_url: https://www.linkedin.com/company/quarterback-to-coach
  gplus_url: https://plus.google.com/110869534711100355975?hl=en
  youtube_url: https://www.youtube.com/channel/UChHMP9DOVwo1SFq0hkh8nbA
  twitter_url: https://twitter.com/QBtoCoach
  instagram_url: https://www.instagram.com/qbtocoach/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'Quarterback to Coach Podcast'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'The place where entrepreneurs come to become leaders.'
  description: 'Jerimiah Taylor and Isacc Guzman swap their secrets on how to polish your leadership skills, shift your business mindset, and empower your team.'
  keywords: 'Entrepreneurs, Leadership skills, business, business mindset, team building, team empowerment'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  # hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
