audit_header: false
title: The McIntosh Team
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Jason McIntosh
  license_number:
  about_markdown: |
    The McIntosh Team's goal is to provide their clients with service that is second to none. As Savannah natives, they pride themselves on their ability to share their knowledge with buyers who may be moving to the area, or have found their dream home and need a team of professionals to assist them in getting it for the best price possible. The McIntosh Team provides sellers with accurate market statistics, aggressive pricing, and marketing strategies that will ensure they get top dollar for their home.
  market: Savannah
  brand: The McIntosh Team
  brokerage:
  address: 329 Commercial Drive, Ste. 100<br>Savannah, GA 31406
  phone: 912-436-6551
  phone_type: Office
  phone2: 912-272-3463
  phone2_type: Mobile
  email: themcintoshteam@gmail.com
  url: http://www.mcintoshrealtyteam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.mcintoshrealtyteam.smarthomeprice.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.mcintoshrealtyteam.com/buy/
  VR_form: http://oi.vresp.com?fid=91587ad52b

sidebar_CTA:
  CTA_image_path: /img/cta-images/001.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: http://www.mcintoshrealtyteam.com/buy/

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheMcIntoshTeam
  linkedin_url: 
  gplus_url: https://plus.google.com/112357686805757201473/about
  youtube_url: https://www.youtube.com/channel/UCdUe_hATTrfe8dqdwnjWmqw
  twitter_url: https://twitter.com/McIntoshTeamKW
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/McIntosh-Realty-Team/
  trulia_url: http://www.trulia.com/profile/jason-and-christina-mcintosh-broker-savannah-ga-2995007/
  yelp_url: 
  podcast_url: https://itunes.apple.com/us/podcast/the-mcintosh-team/id1203020545?mt=2

podcast:
  title: The McIntosh Team
  categories: Education
  image: /img/podcast.pNg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80rem
  hero_text:
  hero_background_hex: '#b40101'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#bbdce5'
  theme_color: '#726359'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "transparent"

buttons:
  button_radius_number: 0px
  button_padding_width_number: 10px
  button_padding_height_number: 15px
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
