audit_header: false
title: Stanley Morrical
description: 'Our mission at Morrical Financial Services is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance.'
show_custom_links: true
custom_links:
  - title: About
    url: http://www.morricalretirementplans.com/

client:
  name: Stanley Morrical
  license_number:
  about_markdown: |
    Morrical Financial Services specializes in 401(k) strategies, offering non-qualified and qualified retirement plan design, staff education, and due diligence services. Morrical Financial Services was founded in 1992 by Stanley Morrical, who has worked to serve the financial needs of the business community for nearly 20 years. Stan works with clients to design and implement 401(k) plans and to help clients understand and meet their fiduciary responsibilities as plan sponsors. Stan, the 401(k) Coach, is an Accredited Investment FiduciaryTM, having successfully completed a specialized program on investment fiduciary standards at the Center for Fiduciary Studies.

  market: San Francisco Bay Area
  brand: Morrical Financial Services
  brokerage:
  address: 851 Burlway Ste 318, Burlingame, CA 94010
  phone: 415-753-3185
  phone_type:
  phone2:
  phone2_type:
  email: smorrical@morrical.com
  url: http://www.morrical.com

CTAs:
  first_CTA_text: Request a Quote
  first_CTA_URL: https://www.emeraldsecure.com/form.cfm?ID=68&UID=16962&SSLID=16962&SN=691400819
  second_CTA_text:
  second_CTA_URL:

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809029';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: "Request a Quote"
    CTA_text: "The benefit from a life insurance policy can provide a steady stream of income for your family. It can also provide liquid capital to pay estate taxes and other obligations."
    CTA_link_text: "Request a Quote"
    CTA_url: https://www.emeraldsecure.com/form.cfm?ID=68&UID=16962&SSLID=16962&SN=691400819

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Get Educated About Your Financial Future
  welcome_text_markdown: >
    Our mission at Morrical Financial Services is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Morrical-Financial-Services-123795974952511/
  linkedin_url: https://www.linkedin.com/in/stanley-morrical-25aa172/
  gplus_url: https://plus.google.com/u/0/b/108627079486586426792/108627079486586426792
  youtube_url: https://www.youtube.com/channel/UChE7Jx_W6lTUwqxvHpFS1Ew
  twitter_url: https://twitter.com/MorFinSvc
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Financial Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more to better prepare yourself for the future.'
  description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance.'
  keywords: 'finance, financial planning, retirement, retirement planning, 401K'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Financial Advisor Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#304876'
  theme_color: '#333333'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
