audit_header: false
title: Dave Knight Real Estate Team Video Blog
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Dave Knight Real Estate Team - your professional Pasadena area Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Dave Knight
  license_number:
  about_markdown: >-
    Dave Knight, our CEO & Listing Specialist, started his career in real estate
    back in 2007 and quickly became a top-producing Agent at Keller Williams.
    Since then, he’s cultivated a cohesive and successful team that relies on
    hard work, intellect, and a strong customer service focus to deliver the best
    experience for our clients.



    While yes, we buy and sell hundreds of homes, our biggest priority is the
    people we help. Our aim to “always come from contribution,” meaning we strive
    to provide value to our clients every step of the way and make sure they are
    being listened to and respected. Our unique team approach means there is
    literally a team of people dedicated to answering your questions, keeping you
    well informed, and getting you the best deal possible.
  market: Pasadena
  brand: Dave Knight Real Estate Team
  brokerage: Keller Williams
  address: '251 S. Lake Ave. Suite 150<br>Pasadena, CA 91101'
  phone: 626-204-3352
  phone_type: Office
  phone2:
  phone2_type: Cell
  email: daveknight@kw.com
  url: www.daveknightrealestate.com
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://daveknightrealestateteam.brivityvaluations.com/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.daveknightrealestate.com/homes-for-sale/#/-2070523458'
  phone_CTA: false

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808383';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

welcome_headline: Get Educated About Real Estate
welcome_text_markdown: 'Our mission at Dave Knight Real Estate Team is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/daveknightrealestateteam/'
  linkedin_url: 'https://www.linkedin.com/in/daveknightrealestate'
  gplus_url: 'https://plus.google.com/u/0/107364944373942438012'
  youtube_url: 'https://www.youtube.com/channel/UCeBhNnLoJqFSwAWYyqJ1U1g'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/DaveKnightRealEstate/'
  trulia_url: 'https://www.trulia.com/profile/dave-knight-agent-pasadena-ca-zg2cwrtn/overview'
  yelp_url: 'https://www.yelp.com/biz/dave-knight-real-estate-team-keller-williams-realty-pasadena'
  podcast_url: 'https://itunes.apple.com/us/podcast/dave-knight-real-estate-group/id1183443300?mt=2'
podcast:
  title: Dave Knight Real Estate Group Podcast
  categories:
  image: /img/Knight_podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Pasadena area Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Dave Knight Real Estate Team - your professional Pasadena area Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Pasadena, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Dave Knight
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text:
  hero_background_hex: '#000000'
  hero_image_path: /img/background.png
brand_color: '#000000'
theme_color: '#000000'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'