audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Andrew Ford
  license_number:
  about_markdown: |
    The Utah Homes Team is comprised of a team of local real estate professionals committed to selling some of the most desired homes in Utah. Selling these "right addresses" is the mission of The Utah Homes Team. Let us know what you're looking for. Please take advantage of the helpful tools on this website, including our exclusive Utah Real Estate search, but also feel free to contact us personally.
  market: Utah County Real Estate
  brand: The Utah Homes Team
  brokerage: Gephardt Approved
  address: 1443 West. 800 North, Suite 201 <br> Orem, UT 84057
  phone: 801-610-9155
  phone_type: Direct
  phone2:
  phone2_type:
  email: andrew@theutahhomes.com
  url: https://www.theutahhomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.theutahhomes.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.theutahhomes.com/results/
  VR_form: http://oi.vresp.com?fid=088b35002b

sidebar_CTA:
  - CTA_image_path: /img/cta-images/005.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: https://www.theutahhomes.com/results/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheUtahHomes
  linkedin_url: https://www.linkedin.com/in/andrewfordutah
  gplus_url: https://plus.google.com/u/0/b/114303237816144250408/114303237816144250408
  youtube_url: https://www.youtube.com/channel/UC2HGm1SGauOESVdUQzATSUw/featured
  twitter_url: https://twitter.com/theutahhomes
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/The-Utah-Homes-Team/
  trulia_url: http://andrewfordrealty.blogspot.com/www.trulia.com/profile/andrew-ford-agent-van-steuban-detroit-mi-1456592
  yelp_url: https://www.yelp.com/biz/the-utah-homes-team-homesmart-advantage-orem
  podcast_url: https://itunes.apple.com/us/podcast/utah-real-estate-podcast-with-andrew-ford/id1235787658?mt=2

podcast:
  title: Utah Real Estate Podcast With Andrew Ford
  categories: Education
  image: http://i.imgur.com/SOOHqvx.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 110
  hero_text: Utah Real Estate Video Blog
  hero_background_hex: '#004964'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#89Abb5'
  theme_color: '#005473'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#89ABB5'
  button_background_color: '#89ABB5'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
