audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Shane & Clint Neal
  license_number: 609739 | 608871
  about_markdown: |
    Clint & Shane Neal, owners of the Neal & Neal Team at Keller Williams Realty, have been growing a rental portfolio, building houses, and flipping properties since 2014. Focusing on the investment side of real estate has allowed them to spin off and create another company, Neal Bros, LLC. Building this brand and company is of utmost importance to bridge the gap between agents and investment opportunities in real estate. They are out-of-the-box thinkers when it comes to creating a win-win situation for all parties involved. If you have a property that needs a lot of work or is in a distressed situation, they would love to earn your business.
  market: San Antonio
  brand: Neal Bros, LLC
  brokerage:
  address: 10999 IH 10 W Suite 175 San Antonio, TX 78230
  phone: 210-844-0393
  phone_type:
  phone2:
  phone2_type:
  email: clint@nealteam.com
  email_type: Email
  email2: shane@nealteam.com
  email2_type: Email
  url: http://www.nealbrosinvestmentgroup.com

# emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808679';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Reach Out To Us
  first_CTA_URL: /contact-us
  # second_CTA_text: Home Search
  # second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Submit a Property"
    CTA_text: "Have a property that might work? Not only will you make the commissions when we purchase the property, but we will give you a 5% equity stake where you will make an additional 5% of the actual profit after we renovate the property and sell it."
    CTA_link_text: "Submit your Property Here"
    CTA_url: /contact-us

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Submit a Property
  welcome_text_markdown: >
    Have a property that might work? Not only will you make the commissions when we purchase the property, but we will give you a 5% equity stake where you will make an additional 5% of the actual profit after we renovate the property and sell it.
  link_text: Submit Your Property Here

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: We purchase <strong>the good, the bad, and the ugly</strong> when it comes to real estate.
  hero_background_hex: '#fff'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#046997'
  theme_color: '#4d4d4d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
