audit_header: false
title: -- CLIENT BRAND --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Debbie Spaulder
  license_number: '#RS-279108'
  about_markdown: |
    Extraordinary Home Experiences! I am committed to exceeding your expectations each and every day. As a Bucks County homeowner for 25 plus years, I can provide whatever area and lifestyle information you require to help you make the best decision. As a top-selling Real Estate Professional and corporate sales professional for more than 20 years, I have the experience, training, and skills to provide you with financing direction, pricing guidelines, and TOP-NOTCH NEGOTIATING.

    Whether you are buying or selling a home, I am experienced in working with a wide range of clients and will work together with you to understand your needs and goals and deliver results. This helps deliver a home-buying or home-selling experience with maximum results. I will work hard to earn your trust and provide a positive experience. I look forward to providing you with the personal attention and superior service you deserve. Debbie Spaulder is the most qualified Real Estate Professional to handle all of your Real Estate needs. Please take a few minutes and give me a call today.
  market: PA
  brand: Keller Williams Real Estate
  brokerage:
  address:
  phone: 215-860-4200
  phone_type: Broker
  phone2: 215-944-5010
  phone2_type: Direct
  email: Debbie@PADreamHomes.com
  url: http://SearchBucksAreaHomes.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://whatsmypahomevalue.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.searchbucksareahomes.com/
  VR_form:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://whatsmypahomevalue.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.searchbucksareahomes.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/debbiespaulderteam/
  linkedin_url: https://www.linkedin.com/in/debbiespaulder
  gplus_url: https://plus.google.com/u/0/+DebbieSpaulder
  youtube_url: https://www.youtube.com/channel/UCs-EDzvCOfRvjO2XJTwkaeA
  twitter_url: https://twitter.com/debbiespaulder
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Debbie-Spaulder/
  trulia_url: http://www.trulia.com/profile/debbie-spaulder-agent-newtown-pa-zg0w7zv7/overview
  yelp_url: http://www.yelp.com/biz/debbie-spaulder-realtor-newtown
  podcast_url: https://itunes.apple.com/us/podcast/bucks-county-real-estate-podcast/id1093943404?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
