audit_header: false
title: The Myles Group
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /client-testimonials
  - title: Featured Listings
    url: 'http://www.themylesgroup.net/results-gallery/?userID=all'
  - title: Brokerage Services Information
    url: 'http://vyralmarketing.s3.amazonaws.com/Jesse%20Myles/IABS%201-0%20FILLED%20IN-%20AAC.pdf'
  - title: Consumer Protection Notice
    url: 'http://vyralmarketing.s3.amazonaws.com/Jesse%20Myles/Consumer%20Protection.pdf'
client:
  name: 'Jesse Myles, REALTORÂ®'
  license_number: 555916
  about_markdown: "The Myles Group is comprised of a team of local real estate professionals committed to selling some of the most desired homes in Greater Fort Hood. Selling these \"right addresses\" is the mission of The Myles Group. Let us know what you're looking for. Please take advantage of the helpful tools on this website, including our exclusive Greater Fort Hood Real Estate search, but also feel free to contact us personally. Each Keller Willams Office is Independently Owned and Operated."
  market: Greater Fort Hood
  brand: The Myles Group
  brokerage: Keller Williams Realty
  address: '12515 Research Blvd., Bldg. 8, #100<br>Austin Tx, 78759'
  phone: 831-402-9572
  phone_type:
  phone2:
  phone2_type:
  email: jesse.myles3@gmail.com
  url: 'http://www.themylesgroup.net'

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808390';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.backatyou.com/home-value/C18CFDE3-2B6B-4F79-88A5-14CCB0D3EA72?r=baygcb_fb_5720'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.themylesgroup.net/results-map/?city=100227%2C100236%2C100230&custom=98897%2C98896%2C98898&midlat=31.025577376963536&midlng=-97.7484455919922&nelat=31.238931209374297&nelng=-97.34023483759768&sort=importdate&status=A&swlat=30.811744623058598&swlng=-98.15665634638674&zoom=11'



sidebar_CTA:
  CTA_image_path: /img/cta-images/004.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: 'https://www.themylesgroup.net/results-map/?city=100227%2C100236%2C100230&custom=98897%2C98896%2C98898&midlat=31.025577376963536&midlng=-97.7484455919922&nelat=31.238931209374297&nelng=-97.34023483759768&sort=importdate&status=A&swlat=30.811744623058598&swlng=-98.15665634638674&zoom=11'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/mylesgroup/'
  linkedin_url: 'https://www.linkedin.com/in/jesse-myles-3653b645/'
  gplus_url: 'https://plus.google.com/107282079909342522356'
  youtube_url: 'https://www.youtube.com/channel/UC_ijOhQ7aWRH6GqL1a-G5Dg'
  twitter_url: 'https://twitter.com/TheMyles_Group'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Jesse-Myles/'
  trulia_url: 'https://www.trulia.com/profile/jesse-myles-agent-killeen-tx-zgy602p9/overview'
  yelp_url:
  podcast_url: 'https://itunes.apple.com/us/podcast/austin-real-estate-podcast-with-jesse-myles/id1215430468?mt=2'
podcast:
  title: Austin Real Estate Podcast with Jesse Myles
  categories:
    - Education
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Real Estate Video Blog
  hero_background_hex: '#000000'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#cc0000'
  theme_color: '#000000'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#cc0000'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'