audit_header: false
title: -- CLIENT BRAND --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: About
    url: /about-us/
  - title: Refer A Friend
    url: 'https://springmortgageteam.agilecrm.com/landing/5635093192245248'
  - title: Our Team
    url: /meet-the-team/
  - title: What is PYT
    url: /what-is-pyt/
  - title: Agent Training
    url: /agent-training/
  - title: Client Testimonials
    url: /client-testimonials

client:
  name: Rob Spring
  license_number: NMLS ID 221178
  about_markdown: |
    Hello, My name is Rob Spring with the Spring Mortgage Team at AmeriFirst Financial of Texas. I am a License Loan Originator and we are a local Mortgage Lender and Broker. Our office is just off the Historic Downtown Square in McKinney, Texas.
    I have been in Mortgage and Real Estate for 15 years. I’ve seen the ups and downs – The Mortgage World has changed quite a bit over the years. I’ve worked for the big bank, the Mom and Pop, ran branches and teams - I’ve found my forever home with AmeriFirst.
  market:
  brand: The Spring Mortgage Team
  brokerage: Amerifirst Financial, Inc.
  address: 204 S. Kentucky Street McKinney, TX 75069
  phone: 214-929-5810
  phone_type:
  phone2:
  phone2_type:
  email: RSpring@AmeriFirst.us
  url:

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808427';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Apply Online
  first_CTA_URL: https://apply.amerifirstloan.com/#/signup?referrerId=rspring%40amerifirst.us
  second_CTA_text: Book an Appoinment
  second_CTA_URL: http://thespringmortgageteam.setmore.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Fill Out Your Application Today
    CTA_text: Get started in the loan process by completing our short loan application.
    CTA_link_text: "Apply Online"
    CTA_url: https://apply.amerifirstloan.com/#/signup?referrerId=rspring%40amerifirst.us

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Choose Your Appointment Option
    CTA_text2: The Spring Mortgage Team at Amerifirst
    CTA_link_text2: "Book An Appoinment"
    CTA_url2: https://thespringmortgageteam.setmore.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for financial
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about the lending process.
    Subscribe to this blog to get the latest news for purchase, refinance, construction or cashout of residential and commercial property.


socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/amerifirst.us
  linkedin_url: http://www.linkedin.com/company/amerifirst-financial-inc.
  gplus_url: https://plus.google.com/101702046196094116736
  youtube_url: https://www.youtube.com/channel/UCwZkiH98Lucj2x7_3eixs7g
  twitter_url: https://twitter.com/SpringMgtTeam
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url: http://www.yelp.com/biz/the-spring-mortgage-team-amerifirst-financial-of-texas-mckinney
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 35
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#EC1D25'
  theme_color: '#3E4753'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
