audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox:
  form:

client:
  name: Alex Yu
  title: 
  license_number: Broker Associate, CIPS<br>BRE 01492674
  about_markdown: |
    Alexander Yu graduated Magna Cum Laude from Chapman University in Business with an emphasis in real estate. His previous careers involved working with high net worth investment advisory clients and a real estate advisory role with JPMorgan Chase. During his tenure working alongside the wealthy and representing the interests of the Fortune 500 bank, he realized that homeowner’s deserved the same quality of service and insight into the changing real estate market. In his free time, he volunteers and donates his resources to causes including youth services, animal care and homelessness.

    He consistently ranks in the top tier of productive agents and prides himself on being a resource and helping others reach their real estate goals. Whether it is a first home or tenth investment property, he is an invaluable asset. For buyers, he provides key market analysis and creates strategies to win offers. For sellers, he provides cutting edge marketing and a global reach to get homes sold for the highest dollar amount in the shortest span of time.
  market: Orange County
  brand:
  brokerage: First Team Estates / Christie's International Real Estate
  address: 4 Corporate Plaza Suite 100 Newport Beach, CA 92660
  phone: 949-682-8880
  phone_type:
  phone2:
  phone2_type:
  email: alexyu@firstteamestates.com
  url: http://www.alexanderyu.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.alexanderyu.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.alexanderyu.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.alexanderyu.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.alexanderyu.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/alexanderyurealestate/?timeline_context_item_type=intro_card_work&timeline_context_item_source=1223239285&__xts__[0]=31.[1223239285%2C%22intro_card%22%2C%7B%7D]
  linkedin_url: https://www.linkedin.com/in/alexhyu/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Alexander-Yu/
  trulia_url:
  yelp_url: https://www.yelp.com/biz/alexander-yu-team-first-team-real-estate-newport-beach
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#231F20'
  theme_color: '#231F20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
