audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Mario Giganti
  license_number:
  about_markdown: |
    Mario C. Giganti is President of Cornerstone Capital Advisors, a 19 person financial advisory firm, where he has overseen significant growth and the transition of the company into one of the largest advisory firms in Northeast Ohio. With over twenty-two years of financial services experience, he leads an advisory team that acts as a personal CFO to help affluent clients preserve wealth, mitigate taxes, protect assets and much more. Additionally, Mario leads the retirement plans services team responsible for helping client’s implement and monitor Cornerstone’s Retirement Bullseye Process.

    Mario holds a variety of professional certifications. He is also an adjunct faculty member with fi360 in Pittsburgh and writes articles on various financial planning topics, 401(k) plan best practices and 401(k) advisory firm practice management.
  market: Corporate 401K Planning
  brand: Cornerstone Capital Advisors
  brokerage:
  address: 1640 Corporate Woods Circle <br> Uniontown, OH 44685
  phone: 330-896-6250
  phone_type: Direct
  phone2: 1-800-448-5319
  phone2_type: Office
  email: info@ccadvisors.com
  url: http://www.ccadvisors.com

CTAs:
  first_CTA_text: Get A Copy Of My Book
  first_CTA_URL: '#contact'
  second_CTA_text: Schedule a Consultation
  second_CTA_URL: http://ccadvisors.com/contact-us/
  VR_form: http://oi.vresp.com?fid=a2e54c7817

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking for Financial Advice?
    CTA_text: Let's talk about how we can help you get Financial Independence
    CTA_link_text: Schedule A Consultation
    CTA_url: http://ccadvisors.com/contact-us/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Get Educated About Retirement & Planning Now
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive knowledgeable tips for preparing yourself for your financial future.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Cornerstone-Capital-Advisors-536985123103533/
  linkedin_url: https://www.linkedin.com/company-beta/1050765/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UC8BwAU2V6TdP9tAMcuodHGw
  twitter_url: https://twitter.com/CCAdvisors
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: The Retirement Bullseye Podcast With Mario Giganti
  categories: Education
  image: http://i.imgur.com/YVy7X4T.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 70
  hero_text: The Retirement Bullseye Video Blog
  hero_background_hex: '#0d4156'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#53473B'
  theme_color: '#53473B'
  theme_text_color: '#353535'
  main_body_color: '#fefaf2'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 0px
  shadow_color: "transparent"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#0d4156'
  button_background_color: '#0d4156'
  button_text_color: '#ffffff'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#761B17'
