audit_header: false
title: Wes Peters Group Real Estate Video Blog
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Wesley Peters
  license_number:
  brand: Wes Peters Group
  brokerage: Keller Williams
  about_markdown: |
    Real Estate expert in the Baltimore metro for almost a decade. Baltimore native, have worked and lived in all the areas I service. Majority of my business is from referrals and repeat clients, firm believer that a happy client is the best advertisement I can have.<br><br>
    Pride myself on being available to my clients around the clock, knowing the contract inside and out and being a tough negotiator. As an active Real Estate investor myself,  my professional network of partners and resources is personally vetted in my years of experience - lawyers, title companies, inspectors, contractors and lenders.<br><br>
    Short Sale and Foreclosure expert. I manage a small, personally trained team of Listing/Buyers agents, Transaction Coordinators and Administrators from my office in Columbia.
  market: Baltimore Metropolitan Area
  address: '6250 Old Dobbin Lane #140<br>Columbia MD 21045'
  phone: 443-499-3839
  phone_type:
  phone2:
  phone2_type:
  email: wes@wespetersgroup.com
  url: http://www.wespetersgroup.com

emma_form:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.wespetersgroup.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.wespetersgroup.com/results/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/005.jpg
    CTA_title: "Whatâ€™s Your Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.wespetersgroup.com/sell/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/001.jpg
    CTA_title2: "Looking to Buy a Home?"
    CTA_text2: "Search the entire MLS for homes located in -- MARKET --"
    CTA_link_text2: "Home Search Tool"
    CTA_url2: http://www.wespetersgroup.com/results/

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/wespetersrealtor/
  linkedin_url: https://www.linkedin.com/company-beta/5295220/?pathWildcard=5295220
  gplus_url: https://plus.google.com/b/102898626941156445277/102898626941156445277?hl=en-US
  youtube_url: https://www.youtube.com/user/wespeters
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/workwithwes/
  trulia_url: https://www.trulia.com/profile/wes-peters-group-agent-columbia-md-zgf6xmrt/overview
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/wes-peters-group-real-estate/id1197464233?mt=2

podcast:
  title: Wes Peters Group Real Estate Podcast
  categories: News &amp; Politics
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50rem
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  hero_text: Baltimore Real Estate Video Blog

site_colors:
  brand_color: '#BF202F'
  theme_color: '#59595C'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header:
  # hero_text: Baltimore Real Estate Video Blog
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 2px
  shadow_color: transparent
  header_text_color: '#59595c'
  header_text_weight: 500

navigation:
  background_color: 'rgba(255,255,255,.8)'
  shadow: '2px 2px 7px rgba(0,0,0,.0)'
  bottom_border_color: '#BF202F'

buttons:
  button_radius_number: 0px
  button_padding_width_number: 10px
  button_padding_height_number: 15px
  button_border_color: '#BF202F'
  button_background_color: '#BF202F'
  button_text_color: '#fff'
  secondary_button_border_color: '#BF202F'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#BF202F'
