audit_header: false
title: Southwest Indiana Real Estate Video Blog with Trae Dauby
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Trae Dauby
  license_number:
  about_markdown: |
    I feel that having the right real estate agent means having an agent who is committed to helping you buy or sell your home with the highest level of expertise in your local market. This means also to help you in understanding each step of the buying or selling process. This commitment level has helped me build a remarkable track record of delivering results. Whether you are an experienced investor or a first time buyer, I can help you in finding the property of your dreams.
  market: Southwest Indiana
  brand: The Dauby Team
  brokerage: Keller Williams
  address: 4004 E Morgan Ave, Suite 200, Evansville, IN 47715
  phone: 812-777-4611
  phone_type:
  phone2:
  phone2_type:
  email: Homes@TheDaubyTeam.com
  url: http://TheDaubyTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.thedaubyteam.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.thedaubyteam.com/results-map/

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808839';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.thedaubyteam.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.thedaubyteam.com/results-map/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/thedaubyteam
  linkedin_url: https://www.linkedin.com/in/trae-dauby-3b827a108/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCkzqKU6CASjROGq_uDmX4Gg
  twitter_url: https://twitter.com/thedaubyteam
  instagram_url: https://www.instagram.com/thedaubyteam/
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/TheDaubyTeam/
  trulia_url: https://www.trulia.com/profile/trae-dauby-agent-evansville-in-zgyr2jt7/
  yelp_url: https://www.yelp.com/biz/the-dauby-team-keller-williams-capital-realty-evansville
  podcast_url: https://itunes.apple.com/us/podcast/southwest-indiana-real-estate-podcast-with-trae-dauby/id1329723793?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
