audit_header: false
title: -- CLIENT BRAND --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Our Listings
    url: http://www.lioceteam.com/our-homes
  - title: About
    url: http://www.lioceteam.com/our-agents/josh-lioce

client:
  name: Josh Lioce
  license_number:
  about_markdown: |
    Naturally, as the broker/owner of Lioce Properties, Inc., Josh has set out to build a business that always exceeds his clients’ expectations, simply because that’s the only way he knows how to work. He has accomplished this goal by assembling a team of highly skilled and knowledgeable professionals who share the same vision and are dedicated to providing a level of service second to none. They believe that a great real estate experience hinges on the relationships we build with their clients. They know that the only way to establish lasting partnerships is through reliability and confidence, and they demonstrate the highest degree of experience and expertise necessary to foster that trust and assurance.
  market: Milford
  brand: Lioce Properties Inc.
  brokerage:
  address: 230 Main Street, Suite 1<br>Milford, MA 01757
  phone: 508-422-9750
  phone_type:
  phone2:
  phone2_type:
  email: Josh@LioceTeam.com
  url: http://LioceTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.eppraisal.com/partner/index/9177/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.lioceteam.com/search/criteria/gp_1/s_2
  VR_form: http://oi.vresp.com?fid=5d757c5752

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://www.eppraisal.com/partner/index/9177/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.lioceteam.com/search/criteria/gp_1/s_2

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/jlioce
  linkedin_url: http://www.linkedin.com/pub/joshua-lioce/8/aa4/66
  gplus_url: https://plus.google.com/103579876021835415912
  youtube_url: https://www.youtube.com/channel/UC6LPlmHQxYlo_D3d6xxYKOw
  twitter_url: https://twitter.com/liocejoshua
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/The-Lioce-Team/
  trulia_url: http://www.trulia.com/profile/joshua-lioce-agent-milford-ma-zgq1b0j5/overview
  yelp_url: https://www.yelp.com/biz/lioce-properties-mendon?osq=Josh+Lioce
  podcast_url: https://itunes.apple.com/us/podcast/milford-real-estate-podcast/id1175138152?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#00a88f'
  theme_color: '#1c3f94'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
