audit_header: false
title: Portland Real Estate Video Blog with Trudy Coler
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title:
    url:
client:
  name: Trudy Coler
  license_number:
  about_markdown: >
    My name is Trudy Coler and I am a full-time, full-service realtor serving the
    Portland, Or marketplace including the surrounding communities of Beaverton,
    Hillsboro, Tigard, Tualatin, West Linn and Lake Oswego. I left over 25 years
    in the corporate world to pursue my dream of taking care of my wonderful
    sellers and buyers as they relocate, downsize, make their first purchase,
    sell and buy their dream house and all of the other things that happen with
    families and home as life happens. My goal is to provide valuable information
    on properties and the process of buying or selling a home and my work is not
    done at closing time. I want you to think of me as a resource for all your
    home and life needs â€“ plumber, electrician, handyman, painter, babysitter,
    dogsitter, housesitter and more!
  brand: '&#x40;Home Property Group, LLC'
  brokerage:
  address: '2301 NW Thurman St.  Suite i Portland, Oregon 97210'
  phone: 971-227-2521
  phone_type:
  phone2:
  phone2_type:
  email: Trudy@colerpdx.com
  url:
CTAs:
  first_CTA_text: Home Evaluation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.realtor.com/'
  phone_CTA: true
  VR_form: 'http://oi.vresp.com?fid=f8f36adbda'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/trudycoler1'
  linkedin_url: 'https://www.linkedin.com/in/ttcoler'
  gplus_url: 'https://plus.google.com/110875466866580044457'
  youtube_url:
  twitter_url: 'https://twitter.com/TrudyColer'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/trudycoler/'
  trulia_url: 'https://www.trulia.com/profile/trudy-coler-agent-portland-or-zg00d30c'
  yelp_url:
  podcast_url: 'https://itunes.apple.com/us/podcast/portland-real-estate-podcast/id1194687560?mt=2'
podcast:
  title: Portland Real Estate Podcast with Trudy Coler
  categories:
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: Portland Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#ed1c24'
  theme_color: '#ed1c24'
  theme_text_color: '#353535'
  main_body_color: '#eeeeee'
  main_body_text_color: '#353535'
buttons:
  button_radius_number: 0
  button_padding_number: 15
  button_border_color: '#eeeeee'
  button_background_color: '#eeeeee'
  button_text_color: '#ed1c24'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'