audit_header: false
title: American Mortgage Group
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Abel Tejeda
  license_number:
  about_markdown: |
      'Our “About Us” web page would be more appropriately called “About You”, as our focus is on closing your loans faster and more efficiently. Our winning strategy consists of a carefully crafted blend of excellent Interest Rates, Flexible Loan Products and Exceptional Customer Service . This concept combines the winning combination: paperless loan process with instant automated loan approvals.'
  market: San Diego
  brand: American Mortgage Group
  brokerage:
  address: 1419 University Ave, Suite C<br>San Diego, CA 92103
  phone: 619-948-2996
  phone_type:
  phone2:
  phone2_type:
  email: abel@abeltejeda.com
  url: http://www.abeltejeda.com

CTAs:
  first_CTA_text: Loan Calculator
  first_CTA_URL: https://www.abeltejeda.com/calculator/What-Is-Missing
  second_CTA_text: Apply Online
  second_CTA_URL: https://abeltejeda-com.mysecureloan.com/applications/page1.php?lng=en

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808804';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Get Your Mortgage Today!"
    CTA_text: "Are you thinking of buying a home in the San Diego area? We can help."
    CTA_link_text: "Get Pre-Qualified"
    CTA_url: https://abeltejeda-com.mysecureloan.com/applications/page1.php?lng=en

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Abel-Tejeda-American-Mortgage-Group-993302390783767
  linkedin_url: https://www.linkedin.com/in/abel-tejeda-8aaba16
  gplus_url: https://plus.google.com/109416905498767543671/about
  youtube_url: https://www.youtube.com/channel/UCTYKaTvO3ETTcSZWhQLieLg
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url: http://www.yelp.com/biz/abel-tejeda-american-mortgage-group-san-diego-2
  podcast_url: https://itunes.apple.com/us/podcast/san-diego-mortgage-podcast-with-abel-tejeda/id1291045797?mt=2

podcast:
  title: '-- MARKET -- Mortgage Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers in the -- MARKET -- Area Real Estate Market'
  description: 'Home loans in San Diego can be complex, but that doesn’t mean you should sign on the dotted line without explanations.'
  keywords: 'Houses for sale in -- MARKET --, mortgage tips, mortgage lender, financing a home, finance, home for sale, home buying, home buying process, property finder, property search, property, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Abel Tejeda's Mortgage Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#203F76'
  theme_color: '#111'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 10px
  shadow_color: rgba (32, 63, 118, 0.8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
