audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Careers
    url: https://dave-friedman-team.breezy.hr/
  - title: Meet the Team
    url: http://clickcharlestonsc.com/agents.php
  - title: Partners
    url: http://clickcharlestonsc.com/resources.php
  - title: Testimonials
    url: http://www.davefriedmantv.com/client-testimonials

client:
  name: Dave Friedman
  license_number:
  about_markdown: |
    Being the #1 realtor not only in families served annually, but also one of the top 2 realtors in Charleston the last 4 years running, it is easy to say that Dave Friedman is committed to his work.

    Despite Dave’s busy professional schedule, he loves spending time with his wife Halley and their two pups. Halley is an Auburn grad, and Dave roots for anything related to Michigan and Detroit as he grew up in southeastern Michigan. Dave and Halley love sports, and staying active in life and in the community. Dave whole heartedly believes in giving back. He has always been and continues to be extremely involved in several non profits. He has organized many successful events for the American Red Cross. Habitat for Humanity, Lifeline and many more.

    Dave has proven that he has what it takes to find or sell your home. He has been a Top Producing Realtor for 18 years, and is in the top 1% of Realtors worldwide. Dave’s also been featured on HGTV’s show House Hunters. He has closed well over 1,500 transactions in his 18+ years practicing real estate, earning countless raving fan reviews. He works hard to get you the deal a buyer is looking for and averages 4% more savings than the average buyer transaction. Dave sells 95% of his listings within 6 days, and within 99.5% of asking price, far exceeding the area average of 95%.

    Dave has spent the past 18+ years analyzing the home buying and selling process for his clients. He has dedicated his time to streamlining the process and improving the results. Dave surrounds himself with the leading experts in the field and is committed to continuing education so that he can always ensure he’s offering the best advice and information for today’s market. Part of Dave’s business philosophy is that it’s better to be great at one thing than to be okay at several things. That’s why Dave has hired a team of experts to work alongside him, from client care coordinators to closing experts, photographers, stagers to professional writers. Dave’s clients know they are always receiving top-notch professionalism and expertise.


  market: Charleston
  brand: Dave Friedman Team
  brokerage: Keller Williams Realty
  address: 496 Bramson Ct Ste 200<br>Mt Pleasant, SC 29464
  phone:  843 972-3833
  phone_type:
  phone2:
  phone2_type:
  email: Dave@DaveFriedmanTeam.com
  url: http://www.ClickCharlestonSC.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808234';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://dave.clickcharlestonsc.com/sell.php?ppc=Vyral+Update&addht=%23VyralUpdate
  second_CTA_text: Home Search
  second_CTA_URL: http://clickcharlestonsc.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: http://clickcharlestonsc.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Dave-Friedman-Real-Estate-at-ReMax/86520966532?ref=br_rs
  linkedin_url: http://www.linkedin.com/in/friedmandavid
  gplus_url: https://plus.google.com/115037410677439559388
  youtube_url: https://www.youtube.com/channel/UCYg5beOA0R1xWVZqukzSNBA
  twitter_url: https://twitter.com/RealEstateRants
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Dave-Friedman/
  trulia_url: http://www.trulia.com/profile/dave-friedman-agent-charleston-sc-9567361/overview
  yelp_url: http://www.yelp.com/biz/dave-friedman-real-estate-mount-pleasant
  podcast_url: https://itunes.apple.com/us/podcast/charleston-real-estate-video-blog-with-dave-friedman/id1242410656?mt=2

podcast:
  title: Charleston Real Estate Video Blog with Dave Friedman
  categories: Education
  image: 'http://i.imgur.com/eBUH7tb.jpg'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: http://i.imgur.com/EUpUpDs.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: <br>
  hero_background_hex: '#FFF'
  post_cover: /img/cover.jpg
  broker_logo: /img/kw.png

site_colors:
  brand_color: '#B40101'
  theme_color: '#4E4A46'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "transparent"

buttons:
  button_radius_number: 0
  button_padding_width_number: 20
  button_padding_height_number: 15
  button_border_color: '#B40101'
  button_background_color: '#B40101'
  button_text_color: '#fff'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
