audit_header: false
title: Standard Mortgage Company with Adam Cohn
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Adam R. Cohn
  license_number: NMLS 294053
  about_markdown: |
    Adam R. Cohn has over 10 years of mortgage banking experience, his knowledge of the business can help you close on you're loan fast and hassle free even in this hectic mortgage and real estate market.
  market:
  brand: Standard Mortgage Company
  brokerage:
  address: 301 W. Atlantic Ave Suite 1 Delray Beach, Florida 33444
  phone: 561-289-0125
  phone_type:
  phone2:
  phone2_type:
  email: adam@standardmortgagecompany.com
  url: http://standardmortgagecompany.com

CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: https://9050993320.mortgage-application.net/WebApp/Start.aspx?oempage=1
  second_CTA_text:
  second_CTA_URL:
  VR_form: http://oi.vresp.com?fid=62c28c3b9b

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Apply Now"
    CTA_text: "Take the time to fill out our loan application"
    CTA_link_text: "Apply Now"
    CTA_url: https://9050993320.mortgage-application.net/WebApp/Start.aspx?oempage=1

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at Standard Mortgage Company is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/AdamIsMyMortgageBanker/
  linkedin_url: https://www.linkedin.com/in/adam-r-cohn-846aa718/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Florida, North Carolina & Kentucky Mortgage Expert <br> Adam R. Cohn
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#022917'
  theme_color: '#298C53'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
