audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Featured Listings
    url: https://www.valleegoldteam.com/results/?OfficeMLS=298
  - title: Finance
    url: https://www.valleegoldteam.com/finance/
  - title: Our team
    url: https://www.valleegoldteam.com/agents/2374-Don-Vallee/
client:
  name: Don Vallee
  license_number:
  about_markdown: |
    We're not just out to sell houses, we connect people with the perfect home. You're important to us and we respect your decision to put your home buying or selling needs in my hands. When you put your trust in us, you will have access to years of experience & knowledge, right at your fingertips.We give working with you our all, whether you're a first time homebuyer, relocating from another state, or downsizing to a retirement home. We share our knowledge & expertise with your every step of the way.
  market: Tucson
  brand: The Vallee Gold Team
  brokerage: Long Realty Company
  address: 1890 East River Road<br>Tucson, AZ 85718
  phone: 520-544-5555
  phone_type:
  phone2:
  phone2_type:
  email: don@donvallee.com
  url: https://www.valleegoldteam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.valleegoldteam.com/sell/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.valleegoldteam.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809013';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: https://www.valleegoldteam.com

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: http://facebook.com/valleegoldteam
  linkedin_url: https://www.linkedin.com/company/vallee-gold-team?trk=cws-cpw-coname-0-0
  gplus_url: https://plus.google.com/u/0/+Valleegoldteam
  youtube_url: https://www.youtube.com/channel/UC-a7ouMxXT7I67FStG7BmIA
  twitter_url: http://twitter.com/valleegoldteam
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/The-Vallee-Gold-Team/
  trulia_url: http://www.trulia.com/profile/don-vallee-agent-park-city-ut-zgfh5bmp/overview
  yelp_url: http://www.yelp.com/biz/vallee-gold-team-tucson
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Real Estate Video Blog
  hero_background_hex: '#06071A'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#CC9900'
  theme_color: '#06071A'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "transparent"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#06071A'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
