audit_header: false
title: askSarita Coaching and Training
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Our Listings
    url: http://www.searchportlandareahomelistings.com/featured/
  - title: About
    url: http://asksarita.com/about

client:
  name: Sarita Dua
  license_number:
  about_markdown: |
    My name is Sarita Dua and I am a realtor serving the Portland, Oregon, marketplace. I service the entire Portland Oregon real estate market, including surrounding communities such as Beaverton, Hillsboro, Tigard, Tualatin, West Linn, Lake Oswego, Aloha, and Hillsboro. Whether you are considering buying a home, selling a home or both, I know this area inside and out.
  market: Portland Real Estate
  brand: The AskSarita Team
  brokerage: Keller Williams Realty Professionals
  address: 9755 SW Barnes Rd Suite 560 <br> Portland, OR 97225
  phone: 503.522.0090
  phone_type: Direct
  phone2:
  phone2_type:
  email: sarita@asksarita.com
  url: http://asksarita.com

emma_form:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://asksarita.com/sellers
  second_CTA_text: Home Search
  second_CTA_URL: http://www.searchportlandareahomelistings.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/005.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: http://www.searchportlandareahomelistings.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/asksaritagroup
  linkedin_url: http://www.linkedin.com/in/asksarita
  gplus_url: https://plus.google.com/u/0/109327571331899857469/about
  youtube_url: https://www.youtube.com/channel/UCVSH8IjZQGdWSmHxEnKh9ag
  twitter_url: https://twitter.com/asksarita
  instagram_url:
  pinterest_url:
  trulia_url: http://www.trulia.com/profile/sarita-dua-agent-portland-or-573316/overview
  zillow_url: http://www.zillow.com/profile/asksarita/
  yelp_url: http://www.yelp.com/biz/asksarita-team-keller-williams-realty-portland
  podcast_url: https://itunes.apple.com/us/podcast/portland-real-estate-podcast/id1183943532?mt=2

podcast:
  title: Portland Real Estate Podcast
  categories: Education
  image: http://i.imgur.com/SLiNoWl.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 65
  hero_text: Portland Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#003868'
  theme_color: '#003868'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
