audit_header: false
title: PalmerHouse Properties
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Kyle Fernandez
  license_number: 2003002868
  about_markdown: 'Today’s buyers and sellers need a trusted resource that can guide them through the complex world of real estate. With my extensive knowledge and commitment to providing only the best and most timely information to my clients, I am your go-to source for real estate industry insight and advice. Buying or selling a home is more than just a transaction: it’s a life-changing experience. Feel free to contact me for all your real estate needs.'
  market: St. Louis
  brand: PalmerHouse Properties STL
  brokerage:
  address: '328 Emmanuel Ct<br>Valley Park, MO 63088'
  phone: 314-323-7999
  phone_type: Kyle
  phone2: 314-369-4743
  phone2_type: Brian
  phone3: 314-651-255
  phone3_type: Jeff
  email: Kyle.Fernandez@PalmerHouseProperties.com
  url: 'http://KyleFernandez.com'
partner:
  name: Brian Preston
  license_number:
  phone: 314-369-4743
  email: Brian.Preston@PalmerhouseProperties.com
  url: 'http://BrianPrestonRealEstate.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.kylefernandez.com/free_home_valuation'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.kylefernandez.com/mls-property-search'
  VR_form: 'http://oi.vresp.com?fid=66cf4960b0'
sidebar_CTA:
  CTA_image_path: /uploads/kyle-arch-cropped.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: 'http://kylefernandez.com/mls-property-search'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender.jpg
  logo_path:
  logo_path_2:
  name: '<b>Jeff Peer</b><br>NMLS 289958'
  brand: USA Mortgage
  phone: 314-651-2558
  email: JPeer@USA-Mortgage.com
  url: 'http://www.palmerhousepropertiesstl.com/financing'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/kylefernandezrealestate'
  linkedin_url: 'https://www.linkedin.com/in/kyle-fernandez-2824512'
  gplus_url: 'https://plus.google.com/118382492541866921969'
  youtube_url: 'https://www.youtube.com/channel/UCueUle-yQz9JqQwsC4Rx5qQ'
  twitter_url: 'https://twitter.com/kylemfernandez'
  instagram_url: 'https://www.instagram.com/kylemfernandez/'
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Kyle-Fernandez/'
  trulia_url: 'https://www.trulia.com/profile/kyle-fernandez-agent-saint-louis-mo-zgb10pjs/overview'
  yelp_url:
  podcast_url: 'https://itunes.apple.com/us/podcast/palmerhouse-properties-real-estate-podcast-kyle-fernandez/id1212414279?mt=2'
podcast:
  title: PalmerHouse Properties Real Estate Podcast with Kyle Fernandez
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  partner_headshot_path: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Real Estate Video Blog
  hero_background_hex: '#091639'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#363966'
  theme_color: '#091639'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 0px
  shadow_color: 'rgba(255, 255, 255, 0.1)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 15
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#091639'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
