audit_header: false
title: '-- CLIENT BRAND --'
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Troy Copeland
  license_number:
  about_markdown: >
    Having a genuine passion for unprecedented client service coupled with an
    expert knowledge of the real estate industry has helped Troy build
    a reputation as an invaluable ally. His high energy, results-driven strategy,
    with a genuine passion for exceeding your expectations, has coined his motto:
    "Your Home is Our Passion".
  market: Frisco
  brand: Troy Copeland Real Estate
  brokerage:
  address: '3233 Libby Lane<br>Frisco, TX 75034'
  phone: 469-844-8769
  phone_type:
  phone2:
  phone2_type:
  email: info@troycopeland.com
  url: 'http://troycopeland.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.friscoarearealestate.com/cma/property-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.friscoarearealestate.com/search/advanced_search/'
  VR_form:
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: /homesearch/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/copelandrealestate/'
  linkedin_url: 'https://www.linkedin.com/in/troyjcopeland'
  gplus_url: 'https://plus.google.com/115934816387268087687'
  youtube_url: 'https://www.youtube.com/channel/UCUM1_F9Sez-4s5fsQvWg67Q'
  twitter_url: 'https://twitter.com/TroyCopelandRE?lang=en'
  instagram_url: 'https://www.instagram.com/troy.copeland/?hl=en'
  pinterest_url: 'https://www.pinterest.com/troyjcopeland/'
  zillow_url: 'https://www.zillow.com/profile/troy026/'
  trulia_url: 'https://www.trulia.com/profile/troy-copeland-agent-frisco-tx-zg862vtx/overview'
  yelp_url: 'https://www.yelp.com/biz/troy-j-copeland-copeland-real-estate-group-frisco'
  realgeeks_url: 'https://www.friscoarearealestate.com/'
  podcast_url: 'https://itunes.apple.com/us/podcast/frisco-real-estate-podcast-with-troy-copeland/id1223770723?mt=2'
podcast:
  title: Frisco Real Estate Podcast with Troy Copeland
  categories:
    - Education
  image: 'http://i.imgur.com/KQw936a.jpg'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Real Estate Video Blog
  hero_background_hex: '#717c83'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#042661'
  theme_color: '#717c83'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#717c83'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
