audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Diane Cardano
  license_number:
  about_markdown: |
    Our team is committed to giving WOW service to our clients during every step of the process. Our goal is to make real estate process FUN, not stressful. We have added benefits and special services to the client before, during, and after the process. It's just another reason that sets us apart from the rest. We pride ourselves on developing relationships with our clients. We want you to know that you can count on us for all of your real estate needs. We want you to be so excited about the quality of services you received from our team, that you refer us to your friends, family, and associates.
  market: Montgomery County
  brand: Cardano Realtors
  brokerage:
  address: 1021 Old York Road Suite 401<br>Abington PA 19001
  phone: 215-576-8666
  phone_type:
  phone2:
  phone2_type:
  email: Diane@CardanoHomeServices.com
  url: http://www.thedianecardanoteam.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808624';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://26homesoldguarantee.smarthomeprice.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://106639.ihf-omnipress.com/email-alerts/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://26homesoldguarantee.smarthomeprice.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://106639.ihf-omnipress.com/email-alerts/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Diane's VIP List
  welcome_text_markdown: >
    Diane and her Team have a mission. It is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Cardano-Realtors/188553414518568
  linkedin_url: http://www.linkedin.com/profile/view?id=13150419&authType=name&authToken=kGGY&trk=tyah
  gplus_url:
  youtube_url: http://www.youtube.com/user/CardanoRealtors
  twitter_url: https://twitter.com/dianecardano/
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Diane-CardanoCasacio/
  trulia_url: https://www.trulia.com/profile/diane-cardano-casacio-agent-abington-pa-zg0zm6sh/overview
  yelp_url: https://www.yelp.com/biz/cardano-realtors-abington
  podcast_url: https://itunes.apple.com/us/podcast/montgomery-county-real-estate-podcast-with-diane-cardano/id1325694063?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Diane Cardano's Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#482684'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  accent_color: '#de9f12'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 7px
  shadow_spread: 13px
  shadow_color: rgba(238, 238, 238, .8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
