audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox:
  form:

client:
  name: Jennie Wolek
  title:
  license_number:
  about_markdown: |
    With more than 15 years of real estate experience under her belt, and as the CEO of The Wolek Real Estate Group, Jennie has learned a thing or two about the industry. Now she wants to share that knowledge with other agents and business owners so you don't have to reinvent the wheel. You will learn how to focus on what is most important - running a great business while helping your clients achieve their goals and dreams.
  market:
  brand: The Wolek Group
  brokerage: Keller Williams Realty
  address: 2651 E. 21st St 100 Tulsa, OK, 74114
  phone: 918-712-2252
  phone_type:
  phone2:
  phone2_type:
  email: Jennie@TheWolekGroup.com
  url: https://www.thewolekgroup.com

CTAs:
  first_CTA_text: Apply Here
  first_CTA_URL: /apply/
  second_CTA_text: Send Us a Referral
  second_CTA_URL: http://www.thewolekgroup.com/contact/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: "Join Our Tulsa Real Estate Team"
    CTA_text: "You will learn how to focus on what is most important - running a great business while helping your clients achieve their goals and dreams."
    CTA_link_text: "Apply Here"
    CTA_url: /apply/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Send Us a Referral"
    CTA_text2:
    CTA_link_text2: "Get Started"
    CTA_url2: http://www.thewolekgroup.com/contact/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/tulsaokrealestate
  linkedin_url: https://www.linkedin.com/in/jenniewolek/
  gplus_url: https://plus.google.com/116503894233070527056
  youtube_url: https://www.youtube.com/channel/UC_9WYLbPpZ-8eZz3u8NMnYg
  twitter_url: https://twitter.com/jenniewolek
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/jwolek/
  trulia_url: https://www.trulia.com/profile/jennie-wolek-agent-tulsa-ok-zgbwwlv0/overview
  yelp_url: http://www.yelp.com/biz/the-wolek-real-estate-group-tulsa
  podcast_url: https://itunes.apple.com/us/podcast/tulsa-ok-real-estate-careers/id1199634583?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#15355B'
  theme_color: '#B01F25'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
