audit_header: false
title: Tools & Training for Central Iowa Real Estate Professionals
description: >-
  A Video Blog about Central Iowa Real Estate; It's industry, and the people
  working in it. Whether you're just starting out, aspiring to begin, or been
  working in the field for a few years, tune in to get updates, tips, tricks and
  more!
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Misty SOLDwisch
  license_number:
  about_markdown: >-
    In real estate since 1999, and a broker/owner since 2007, Misty Soldwisch
    has been leading the Central Iowa real estate market with innovative
    approaches to marketing, systems, and coaching while building a top
    producing team with a “specialist” approach. &nbsp;Misty launched the Better
    Homes and Gardens Real Estate brand in Iowa in 2017 and is CEO of the
    company.
  market: Central Iowa
  brand: Be Better DSM - Real Estate Coaching
  brokerage: Better Homes and Gardens Real Estate Innovations
  address: '117 East Salem Avenue<br>Indianola, IA 50125'
  phone: 515-346-6803
  phone_type:
  phone2:
  phone2_type:
  email: Misty@BHGInnovations.com
  url: http://BHGInnovations.com

client2:
  name: Aaron Moulton
  license_number:
  about_markdown: |
    Aaron grew up in real estate, and has been around the real estate business for nearly 16 years now, with positions in both mortgage banking and residential real estate companies. Aaron is a sales training guru with an emphasis on understanding how finance knowledge can help our agents help our clients. Aaron joined Better Homes and Gardens Real Estate Innovations as Director of Business Development, and his job is to find and develop talent!
  brand: Be Better DSM - Real Estate Coaching
  brokerage: Better Homes and Gardens Real Estate Innovations
  address: '9325 Bishop Drive #110<br>West Des Moines, IA 50365'
  phone: 515-218-7740
  email: AaronM@BHGInnovations.com
  url: http://BHGInnovations.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809043';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how we can take your business to new heights.
    CTA_link_text: Join Our Team
    CTA_url: /join-our-team/
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
welcome_box:
  welcome_headline: How to Sell More Homes
  welcome_text_markdown: >
    Whether you are just starting out, or you are licensed Broker, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/BeBetterDSM/'
  linkedin_url: 'http://www.linkedin.com/in/mistysold/'
  gplus_url: 'https://plus.google.com/u/0/101245833147854335879'
  youtube_url: 'https://www.youtube.com/channel/UC6QI2aC5ZGGsZZurGK0Fodw'
  twitter_url: 'https://twitter.com/MistySOLDTeam'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Misty-SOLDwisch-Team/'
  trulia_url: >-
    http://www.trulia.com/profile/the-misty-soldwisch-team-broker-indianola-ia-236926/overview
  yelp_url: 'http://www.yelp.com/biz/the-misty-soldwisch-home-selling-team-indianola'
  podcast_url:
  instagram2_url: https://www.instagram.com/bhginnovations/
  facebook2_url: https://www.facebook.com/bhginnovations/
  # facebook3_url: https://www.facebook.com/BeBetterDSM/

podcast:
  title: Central Iowa Real Estate Careers and Training Podcast with Misty Soldwisch
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: Boost your Career with Veteran Real Estate Agent Misty Soldwisch
  description: >-
    A Podcast about Central Iowa Real Estate; It's industry, and the people
    working in it. Whether you're just starting out, aspiring to begin, or been
    working in the field for a few years, tune in to get updates, tips, tricks
    and more!
  keywords: >-
    -- MARKET -- Real Estate, Real Estate Careers, Real Estate Professionals,
    Realtors, Real estate industry, how much do realtors make
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  client2_headshot_path: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Central Iowa Real Estate Careers and Training Video Blog
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#439639'
  theme_color: '#333333'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
