audit_header: false
title: Baltimore Real Estate Video Blog with Seth and Alyce Dailey
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Seth and Alyce Dailey
  license_number:
  about_markdown: |
    The Dailey Group is comprised of a team of local real estate professionals committed to selling some of the most desired homes in Greater Baltimore Area. Selling these "right addresses" is the mission of The Dailey Group. Let us know what you're looking for. Please take advantage of the helpful tools on this website, including our exclusive Greater Baltimore Area Real Estate search, but also feel free to contact us personally.
  market: Baltimore
  brand: The Dailey Group
  brokerage: Keller Williams Gateway
  address: 8015 Corporate Drive, Suite C<br>Baltimore, MD 21236
  phone: 800-214-1245
  phone_type: Office
  phone2:
  phone2_type:
  email: Hello@TheDaileyGroup.com
  # email_type: Seth
  # email2: Alyce@TheDaileyGroup.com
  # email2_type: Alyce
  url: http://TheDaileyGroup.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808429';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.thedaileygroup.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.thedaileygroup.com

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: https://www.thedaileygroup.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.thedaileygroup.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/thedaileygroup
  linkedin_url: https://www.linkedin.com/company-beta/1257880/
  gplus_url: https://plus.google.com/b/115391039795230903679
  youtube_url: https://www.youtube.com/channel/UCyMYgJtDz9h4XkjT_4dh6OQ
  twitter_url: http://twitter.com/thedaileygroup
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/The-Dailey-Group/
  trulia_url: https://www.trulia.com/profile/the-dailey-group-agent-baltimore-md-zg1683nj/overview
  yelp_url: https://www.yelp.com/biz/the-dailey-group-keller-williams-gateway-baltimore
  podcast_url: https://itunes.apple.com/us/podcast/baltimore-real-estate-podcast-with-seth-and-alyce-dailey/id1304453289?mt=2

podcast:
  title: Baltimore Real Estate Podcast with Seth and Alyce Dailey
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
