audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Melissa Thompson
  license_number:
  about_markdown: |
    Melissa Thompson has a qualified, well-skilled team to handle all of the clients’ needs, yet provide personal attention to each. The Melissa Thompson Team is the leading group of Memphis realty experts with the mission of providing the utmost personal service to every client and providing each with the “Key to Memphis.”

    Contact The Melissa Thompson Team with confidence! We want to be YOUR real estate agent. As your trusted, professional real estate partner, we will help you find the best home in your area within your price range and together with you will sell your home, for as much as the market will bear and as quickly as possible.
  market: Memphis
  brand: Your Key To Memphis
  brokerage: Crye-Leike Realtors
  address: 6525 N. Quail Hollow Road Memphis, TN 38120
  phone: 901-756-8900
  phone_type: Office
  phone2: 901-729-9526
  phone2_type: Direct
  email: Melissa@YourKeyToMemphis.com
  url: http://YourKeyToMemphis.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://yourkeytomemphis.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.yourkeytomemphishomes.com/results/
  VR_form: http://oi.vresp.com?fid=e2a69a347d

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://yourkeytomemphis.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.yourkeytomemphishomes.com/results/

lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender.jpg
  # logo_path: /img/logo.png
  logo_path_2: /img/lenderlogo.jpg
  name: Wendy Thompson
  nmls: 'NMLS #504814'
  brand: Mortgage Loan Originator
  address: 6000 Poplar Avenue, Ste. 250 Memphis, TN 38119
  phone: 901-461-8858
  email: Wendy@TheWendyThompsonTeam
  url: http://thewendythompsonteam.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: http://www.facebook.com/YourKeyToMemphis
  linkedin_url: http://www.linkedin.com/in/melissayourkeytomemphis
  gplus_url: https://plus.google.com/111712258542671998374
  youtube_url: https://www.youtube.com/channel/UC3TKrdkRqLbwGEjbDk_7HfQ
  twitter_url: http://twitter.com/MelissaMemphis
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Melissa-Thompson/
  trulia_url: https://www.trulia.com/profile/melissa-thompson-agent-memphis-tn-zgzp20m4/overview
  yelp_url: https://www.yelp.com/biz/melissa-thompson-your-key-to-memphis-team-memphis
  podcast_url: https://itunes.apple.com/us/podcast/memphis-real-estate-podcast-with-melissa-thompson/id1238303802?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#701400'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(50, 50, 50, .4)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
