audit_header: false
title: Utah Real Estate Video Blog with The Canovo Group
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
  -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: 'http://unbouncepages.com/join-canovo/'
  - title: Client Testimonials
    url: /client-testimonials
client:
  name: The Canovo Group
  license_number:
  about_markdown: >
    The Canovo Group is one of Utah’s top real estate teams. With over a decade
    of experience and hundreds of real estate transactions under their belt, The
    Canovo Group understands what it takes to get results for their clients.


    They believe in straight talk. They understand that what you most want and
    need right now is answers, honest advice, realistic expectations and expert
    help during the buying or selling process.


    The Canovo Group focus heavily on internet marketing. They believe that it’s
    their job to stay on the cutting edge of real estate technology so their
    clients have a competitive advantage.
  brand: The Canovo Group
  brokerage: Keller Williams Westfield Realty
  address: '841 North 900 West Orem, UT 84057'
  phone: 801-214-1662
  phone_type:
  phone2:
  phone2_type:
  email: Info@canovogroup.com
  url: 'https://www.canovogroup.com'
emma_form: >-
  <script
  id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808651';</script><script
  src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.canovogroup.com/contactus/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.canovogroup.com/'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free -- MARKET -- Home Value Report
    CTA_url: 'https://www.canovogroup.com/contactus/'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: 'http://www.canovogroup.com/'
lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.png
  logo_path: /img/lender-logo.jpg
  logo_path_2: /img/lender-logo2.png
  name: Austin Ingersoll
  brand: Lender Co.
  phone: 801-901-6203
  email: austin.ingersoll@AcademyMortgage.com
  url: 'http://www.academymortgage.com/austiningersoll'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/CanovoGroup'
  linkedin_url: 'https://www.linkedin.com/in/david-robinson-27aa9225'
  gplus_url: 'https://plus.google.com/+CanovoGroupSells'
  youtube_url: 'https://www.youtube.com/user/CanovoGroup'
  twitter_url:
  instagram_url: 'https://www.instagram.com/canovogroup/'
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/DavidTheon/'
  trulia_url: 'http://www.trulia.com/profile/david-t-robinson-broker-orem-ut-8292480/'
  yelp_url: 'http://www.yelp.com/biz/david-t-robinson-real-estate-team-orem'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/utah-real-estate-podcast-with-david-robinson/id1280558665?mt=2
podcast:
  title: Utah Real Estate Podcast with David Robinson
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 15px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'