audit_header: false
title: Marketing Luxury Real Estate Consulting Video Blog with Michael LaFido
description: A Video Blog about -- MARKET -- ; its industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox:
  form:

client:
  name: Michael LaFido
  title:
  license_number:
  about_markdown: |
    The Marketing Luxury Group is recognized as an international creative force in the luxury home industry. Founder Michael LaFido has been recognized as one of the top Real Estate Marketers worldwide.
  market: Marketing Luxury Listings
  brand: Marketing Luxury Group
  brokerage:
  address: 401 W. Ontario Suite 401<br>Chicago, IL 60654
  phone: 888-930-8510
  phone_type:
  phone2:
  phone2_type:
  email: Mike@TheLaFidoTeam.com
  url: http://MarketingLuxuryGroup.com

CTAs:
  first_CTA_text: Request a Consultation
  first_CTA_URL: /contact/
  second_CTA_text: Luxury Listing Blueprint!
  second_CTA_URL: http://luxurylistingblueprint.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Market Luxury Homes the right way?
    CTA_text: Let's talk about how the Luxury Listing Specialist Certification can take your business to the next level.
    CTA_link_text: Request a Consultation
    CTA_url: /contact/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Download your Luxury Listing Blueprint Today!
    CTA_text2: Discover the Secrets to Becoming a Certified Luxury Listing Specialist.
    CTA_link_text2: Luxury Listing Blueprint
    CTA_url2: http://luxurylistingblueprint.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MarketingLuxuryGroup/
  linkedin_url: https://www.linkedin.com/in/mikelafido
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UC6Ngom-zub7lpnLTJFEuWbg
  twitter_url: https://twitter.com/lafido
  instagram_url: http://instagram.com/marketingluxurygroup
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Michael-Lafido/
  trulia_url: http://www.trulia.com/profile/michael-lafido-agent-chicago-il-zgcj042g/overview
  yelp_url:
  podcast_url:

podcast:
  title: Marketing Luxury Real Estate Podcast Video Blog with Michael LaFido
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 20
  hero_text: Marketing Luxury Real Estate Consulting Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#082943'
  theme_color: '#000000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
