audit_header: false
title: '-- CLIENT BRAND --'
description: >-
  Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET --
  real estate advice. Whether you are a buyer, seller, or investor, our team of
  professionals can answer any questions you might have about real estate. If
  you are looking to buy or sell a home, you can get all the information and the
  latest updates, tips, and tricks from The -- CLIENT BRAND --, your
  professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Testimonials
    url: /client-testimonials/
  - title: Featured Listings
    url: www.rothteam.shorewest.com/search/Search/agentid_5281/presentation_P/pa_5281/nts_5/sd_AL/sc_lp_Listing_Price%20DESC/  
    
client:
  name: Mike Roth
  license_number:
  about_markdown: >
    Over the last twelve months, we have closed over 210 transactions – compare
    this to the average real estate agent that sold less than four homes in the
    same period of time. More importantly, we are bringing our sellers an
    average of 96% or more of the asking price. This is all done on a timetable
    of 35 days that the home being on the market.  I’ve been in the real estate
    business for over 37 years and have closed over 6,000 deals. There hasn’t
    been a problem we’ve come across that we can’t solve in today’s market –
    especially in the challenging market we have today. We will also determine
    the best price that you can receive in this market. One of the biggest
    problems in this industry is the lack of communication between the seller
    and their agent. We have a dedicated team that will be available to you
    seven days a week. You can rest assured knowing that all of your questions
    will be answered and you will be updated through every step of the
    transaction. You also can expect Weekly Activity Reports that include how
    many hits your listing has gained from the internet, TV advertising, and
    feedback we’ve received from the buyers. When you’re ready to sell your
    home, give the Roth Team a call or send us an email.'
  market: Greater Milwaukee
  brand: The Roth Team
  brokerage: Shorewest Realtors
  address:
  phone: 262.797.6453
  phone_type: Office
  phone2: 262.798.1162
  phone2_type: Direct
  email: rothteam@shorewest.com
  url: 'http://RothTeam.Shorewest.com'
  
emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808421';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
  
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://rothteam.shorewest.com/vp/AgentServlet?SITE=SHOREW&ScreenID=AGENT_WHATS_MY_HOME_WORTH&pres_agent=5281
  second_CTA_text: Home Search
  second_CTA_URL: http://rothteam.shorewest.com/vp/SearchServlet?SITE=SHOREW&ScreenID=AGENT_SEARCH_LISTING&pres_agent=5281
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: What’s Your Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free Home Value Report
    CTA_url: http://rothteam.shorewest.com/vp/AgentServlet?SITE=SHOREW&ScreenID=AGENT_WHATS_MY_HOME_WORTH&pres_agent=5281
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: http://rothteam.shorewest.com/vp/SearchServlet?SITE=SHOREW&ScreenID=AGENT_SEARCH_LISTING&pres_agent=5281
lender:
  show_section: true
  header_text: Preferred Lender
  headshot_path: /img/lender_headshot.jpg
  logo_path: /img/lender_logo.png
  name: 'Allan L. Ripple, CRMS'
  brand: JOHNSON BANK
  phone: 414-852-7022
  email: ARipple@JohnsonBank.com
  license_number:
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: >-
    https://www.facebook.com/pages/Roth-Team-Real-Estate-Tips-Trends-Homes/136963786378401
  linkedin_url: 'http://www.linkedin.com/in/rothteam1'
  gplus_url: 'https://plus.google.com/u/0/112410435343799616390'
  youtube_url: 'https://www.youtube.com/channel/UCO7jtl0aHG-tsEw6pX1hcaw'
  twitter_url: 'https://twitter.com/SellMilwaukee'
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: >-
    https://itunes.apple.com/us/podcast/shorewest-greater-milwaukee/id911884769?mt=2
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#273d90'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'