audit_header: false
title: Roanoke Real Estate Careers and Training Video Blog with Damon Gettier
description: A blog about real estate careers and training in the Roanoke, Virginia area, brought to you by Damon Gettier of Damon Gettier & Associates.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Damon Gettier
  license_number:
  about_markdown: |
    Damon Gettier & Associates Realtors specializes in Roanoke, Lynchburg, Smith Mountain Lake and New River Valley VA Real Estate! Founder Damon Gettier formed Damon Gettier & Associates REALTORS ("DGA") out of an intense desire to give his Clients the attention, communication and service they deserved. We do the most for our clients and provide the absolute best service in Lynchburg, Roanoke, Smith Mountain Lake and the New River Valley. We realize that our clients are our business, our future, our lives, and we care. We are not here to sell you a home, we are here to serve. In serving you, we know that our needs will be met. We know that a home is not a home until our clients make it their home. It is our desire to make that process the easiest, most exciting, pain free, experience possible by treating you honestly, ethically, while exhibiting extreme competence and knowledge. We want you to know and trust that we care, not through our words, but through our service and friendship.
  market: Roanoke
  brand: Damon Gettier & Associates
  brokerage:
  address: 1611 E Main Street Salem, VA 24153
  phone: 540-314-1199
  phone_type:
  phone2:
  phone2_type:
  email: Damon@DamonGettier.com
  url: http://www.DamonGettier.net

CTAs:
  first_CTA_text: Apply Now
  first_CTA_URL: http://damongettier.com/join/
  # second_CTA_text: Home Search
  # second_CTA_URL: http://www.damongettier.net/our-homes

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808706';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: "Are You Interested In A Real Estate Sales Career?"
    CTA_text: "Join the #1 Real Estate Team in Central and SW Virginia"
    CTA_link_text: "Book a Free Business Strategy Session"
    CTA_url: http://damongettier.com/join/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: http://www.damongettier.net/our-homes

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender_headshot.jpg
  logo_path: /img/lender_logo.jpg
  logo_path_2:
  name: Joel Balsley
  title: Mortgage Banker
  license_number: 'NMLS #210455, Licensed in VA'
  phone: 540-278-1430
  email: JoelBalsley@AtlanticBay.com
  url: http://AtlanticBay.com/JoelBalsley

welcome_box:
  welcome_headline: How to Sell More Homes
  welcome_text_markdown: >
    Whether you are just starting out, or you are licensed Broker, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/DamonGettierandAssociates
  linkedin_url: http://www.linkedin.com/in/damongettier/
  gplus_url: https://plus.google.com/115577070629118145299
  youtube_url: http://www.youtube.com/user/RoanokeLiving
  twitter_url: https://twitter.com/DamonGettier
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/damongettier1/
  trulia_url: http://www.trulia.com/profile/damon-gettier-broker-roanoke-va-198857/reviews
  yelp_url: http://www.yelp.com/biz/damon-gettier-and-associates-roanoke?nb=1
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Boost your Career with Veteran Real Estate Agent Damon Gettier'
  description: 'A podcast about real estate careers and training in the Roanoke, Virginia area, brought to you by Damon Gettier of Damon Gettier & Associates.'
  keywords: '-- MARKET -- Real Estate, Real Estate Careers, Real Estate Professionals, Realtors, Real estate industry, how much do realtors make'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Careers & Training Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#6F010F'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(250, 250, 250, .5)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
