audit_header: false
title: John Meulstee 
description: A Video Blog about -- MARKET -- Real Estate; It's industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: John Meulstee
  license_number: RS303707
  about_markdown: |
       The Realty One Group Legacy mission is to “Inspire & Empower people to create a better life through real estate!” and they are doing this with John’s support and guidance. In December of 2016, John and his operations team launched this company with a vision to become the largest residential real estate brokerage in the Delaware Valley by living this mission. Realty One Group Legacy is a thriving group of agents building their businesses and teams with John’s support and mentoring. John works to consistently increase his knowledge so that he is able to help other agents reach their goals and serve their clients to the best of their ability. John’s personal mission is to help as many people as he can to reach their personal goals by improving their businesses. This benefits agents, buyers, sellers, and investors alike. With his dedication to learning and sharing, John stays connected with the industry through his affiliation with the Realtor Association, Realty One Group, and Real Estate B-School Boardroom (a mastermind group of elite agents from around the country with similar values and missions.) If you are an agent looking for a place to create a successful business through sustainable systems and with incredible support, contact John Meulstee at Realty One Group Legacy today. “By freely giving and sharing everything I have learned in this business and by bringing on top quality people and agents, Realty One Group Legacy will have the most powerful sales force in every market we enter.” - John Meulstee
  market: Realty One Group Legacy
  brand: John Meulstee 
  brokerage:
  address: 405 Farm Lane Doylestown, PA 18901
  phone: 215-622-9772
  phone_type:
  phone2:
  phone2_type:
  email: jm@roglegacy.com
  url: http://www.roglegacy.com

CTAs:
  first_CTA_text: Request a Consultation
  first_CTA_URL: http://www.roglegacy.com/contact-us/
  # second_CTA_text: Apply
  # second_CTA_URL: /apply/
  VR_form: http://oi.vresp.com?fid=e0ad573cbf

sidebar_CTA:
  - CTA_image_path: /img/cta-images/006.jpg
    CTA_title: Looking to Build Your Real Estate Career?
    CTA_text: Let's talk about how we can take your business to new heights.
    CTA_link_text: Request a Free Strategy Session
    CTA_url: http://www.roglegacy.com/contact-us/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: How to Sell More Homes
  welcome_text_markdown: >
    Whether you are just starting out, or you are licensed Broker, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ROGLegacy/
  linkedin_url: https://www.linkedin.com/in/john-meulstee-0705435/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/John-Meulstee/
  trulia_url: https://www.trulia.com/profile/john-meulstee-agent-doylestown-township-pa-zg8xb86m/overview
  yelp_url: https://www.yelp.com/biz/john-meulstee-home-selling-team-doylestown
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Boost your Career with Veteran Real Estate Agent John Meulstee'
  description: A Podcast about Real Estate; It's industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
  keywords: 'Real Estate Careers, Real Estate Professionals, Realtors, Real estate industry, how much do realtors make'
  author: 'John Meulstee'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Real Estate Careers <br> and Training Video Blog
  hero_background_hex: '#91CEC6'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: black
  theme_color: '#C6AA5E'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 3
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
