audit_header: false
title: The Wicker Homes Group
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from The Wicker Homes Group your professional
  Northern Virginia Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Debbie's List
    url: >-
      https://www.yumpu.com/en/document/view/55881214/debbies-list-virginia-contractors-2016-q4
  - title: About
    url: 'http://www.wickerhomesgroup.com/meet-the-team'
  - title: 19-Point Selling System
    url: >-
      https://www.yumpu.com/en/document/view/55525349/wicker-homes-group-listing-presentation-2016
  - title: Why Sell With Us
    url: 'http://sellwithwhg.com/'
client:
  name:
  license_number:
  about_markdown: >-
    At the Wicker Homes Group we are committed to helping families and
    individuals find a place they love to call home. And we're committed to
    helping our clients receive top dollar for their homes to grow their wealth
    through real estate. Let us know how we can help you. Please take advantage
    of the helpful tools on this website, including our exclusive Loudoun &
    Fairfax County Home Search. And of course, feel free to call us with any
    real estate questions.
  market:
  brand: Wicker Homes Group
  brokerage: Keller Williams Realty Loudoun Gateway
  address: '20130 Lakeview Center Plaza Suite 110<br>Ashburn, VA 20147'
  phone: 571-210-4997
  phone_type:
  phone2:
  phone2_type:
  email: info@wickerhomes.com
  url: 'http://www.wickerhomesgroup.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.wickerhomesgroup.com/what-s-my-home-worth'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.wickerhomesgroup.com/search/criteria/cty_1736,1762,4125/gp_1/s_2'
  VR_form:
sidebar_CTA:
  - CTA_image_path: /img/cta-images/007.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes in Northern Virginia
    CTA_link_text: Home Search Tool
    CTA_url: 'http://www.wickerhomesgroup.com/search/criteria/cty_1736,1762,4125/gp_1/s_2'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >-
    Our mission at the Wicker Homes Group is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/WickerHomesGroup/'
  linkedin_url: 'https://www.linkedin.com/company-beta/13217890/?pathWildcard=13217890'
  gplus_url: 'https://plus.google.com/+WickerHomesGroupAshburn/posts'
  youtube_url: 'https://www.youtube.com/user/wickerhomesgroup'
  twitter_url: 'https://twitter.com/wickerhomes'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Wicker-Homes-Group/'
  trulia_url: >-
    http://www.trulia.com/profile/debbie-wicker-broker-ashburn-va-364181/overview
  yelp_url: 'http://www.yelp.com/biz/wicker-homes-group-re-max-ashburn'
  podcast_url:
podcast:
  title: Northern Virginia Real Estate Video Blog with The Wicker Homes Group
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /uploads/gold-logo-1.png
  logo_width_number: 40
  hero_text: Northern Virginia<br>Real Estate Blog
  hero_background_hex: '#191919'
  hero_image_path: /uploads/stonetowerwinerywickersbackgroundcropped.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#c3932f'
  theme_color: '#191919'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#05091e'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'