audit_header: false
title: John Meulstee Home Selling Team Video Blog
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: John Meulstee
  license_number: RS303707
  about_markdown: |
       Growing up in Central Bucks and living here all of my life, I enjoy being a long time resident of Doylestown and am committed to our community. After graduating from CB West and becoming a Business Management Systems major at Shippensburg University my life changed on September 11th, 2001.
       After the atrocities of September 11th, 2011, I left college and enlisted for five-years with the United States Marine Corp where I became a Helicopter Crew Chief. During my time in service, I was meritoriously promoted twice and served two seven month tours in Iraq. Honor, Courage and Commitment, the US Marine Corps values, were imprinted in me deeply during this time. My desire to serve and to lead are evident in the commitment I bring to my team every day.
       After finishing my duties in the Marine Corps in 2007, I decided to start my business life as a Realtor after reading the book Rich Dad, Poor Dad. This book inspired me to strive for a bigger life than I had growing up and helped pave the way for the successes I would quickly have in business.
       In ten short years I have built a team that annually sells more homes in Bucks and Montgomery Counties than any other agent. In 2016 The John Meulstee Home Selling Team sold 119 homes for a sales volume of over $37M and is on pace for over 150 home sales and over $50M in sales volume this year.
  market:
  brand: John Meulstee Home Selling Team
  brokerage: Realty One Group Legacy
  address: 405 Farm Lane Doylestown, PA 18901
  phone: 215-603-3307
  phone_type:
  phone2:
  phone2_type:
  email: john@meulsteeteam.com
  url: http://johnmeulsteeteam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://instantpahomevalues.com/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.newpahomelistings.com/
  VR_form: http://oi.vresp.com?fid=e0ad573cbf

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://instantpahomevalues.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.newpahomelistings.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at John Meulstee Home Selling Team is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/JohnMeulsteeRealEstate/
  linkedin_url: https://www.linkedin.com/in/john-meulstee-0705435/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/John-Meulstee/
  trulia_url: https://www.trulia.com/profile/john-meulstee-agent-doylestown-township-pa-zg8xb86m/overview
  yelp_url: https://www.yelp.com/biz/john-meulstee-home-selling-team-doylestown
  podcast_url:

podcast:
  title:
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the  Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from John Meulstee Home Selling Team - your professional Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Lane Doylestown, PA, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'John Meulstee'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#C6AA5E'
  theme_color: black
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 8px
  shadow_color: '#ffffff'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
