audit_header: false
title: Colemere Realty and Associates
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from Colemere Realty and Associates - your
  professional Wasatch Front Real Estate Agents.
show_custom_links:
custom_links:
  - title:
    url:
client:
  clients:
    - name: Bryan Colemere
      client_headshot_path: /img/headshot1.jpg
      license:
      phone: 801-699-4266
      email: bryan@colemererealty.com
      about_markdown: >
        Bryan is a strong believer that the principles of integrity and ethics
        should always be the core motive both in his career in real estate, as
        well as in his personal life. This, combined with his experience and
        competency as a 3rd generation realtor has resulted in his loyal
        clientele who know he is passionate and will make a difference to impact
        people for the better regardless of the situation at hand. Whether he is
        confronted with complex transactions, or the simplest situations, he is
        creative, resourceful, and puts the same hard work and dedication into
        each scenario. Bryan is a husband and father of three. In his personal
        life, he enjoys family time, coaching his kids, outdoor activities, and
        playing the piano. He has been featured as a guest speaker on webinars,
        podcasts, and at national conferences. He loves sharing his knowledge
        and experience with others by speaking on the important role real estate
        agents have, and the art of selling Real Estate properly.
    - name: Scott Colemere
      client_headshot_path: /img/headshot2.jpg
      license:
      phone: 801-403-8565
      email: scott@colemererealty.com
      about_markdown: >
        Scott is a third generation REALTOR and has been in the business since
        1997. He is in the top 5% of all agents in the Salt Lake Board of
        Realtors for sales completed. He has been recognized by the Salt Lake
        Board for outstanding sales performance, professionalism and Board
        participation.
  market: Wasatch Front
  brand: Colemere Realty Associates
  brokerage:
  address: '9661 S 700 E<br>Sandy, UT 84070'
  office_phone: 801-272-8192
  office_email: info@colemererealty.com
  url: 'http://colemererealty.com/'
  first_CTA_text: Home Evaluation
  first_CTA_URL: 'https://www.colemererealty.com/sell/'
  second_CTA_text: Home Search
  second_CTA_URL: 'https://www.colemererealty.com/buy/'
  VR_form: 'http://oi.vresp.com?fid=c3a9b44641'
  about_header: About Bryan and Scott Colemere
welcome_headline: Get Educated About Your Real Estate
welcome_text_markdown: >-
  Our mission at Colemere Realty and Associates is to be your best resource for
  real estate advice. Our team of professionals can answer any questions you
  might have about real estate. Subscribe to this blog to get the latest news on
  real estate and receive expert tips for preparing yourself for your buying or
  selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/Colemere-Realty-Associates-207059249365713/'
  linkedin_url: 'https://www.linkedin.com/in/bryan-colemere-21b4a03/'
  gplus_url: 'https://plus.google.com/b/104681953481099879209/104681953481099879209?hl=en'
  youtube_url: 'https://www.youtube.com/channel/UC3MPsAkkbFjc6lNxgDshMLQ'
  twitter_url: 'https://twitter.com/bryancolemere'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/bcolemere/'
  trulia_url:
  yelp_url: 'https://www.yelp.com/biz/bryan-colemere-colemere-realty-riverton'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/colemere-realty-associates/id1177583830?mt=2
podcast:
  title: Colemere Realty and Associates Real Estate Podcast
  categories:
  image: /img/colemere_podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the Portland
    Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from Colemere Realty and Associates - your
    professional Wasatch Front Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in Wasatch Front,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Bryan Colemere
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_text:
  hero_background_hex: '#0b2972'
  hero_image_path: /img/background.jpg
brand_color: '#0b2972'
theme_color: '#0b2972'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'