audit_header: false
title: Athens Real Estate Video Blog with Justin Woodall
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Justin Woodall
  license_number:
  about_markdown: |
    We seek to outperform the industry average while exceeding the expectations of our clients. 80% of the homes we sell are under contract in less than 90 days and buyers we work with have priority access to the hottest new listings before others know they are for sale.
  market: Athens
  brand: Woodall Realty Group
  brokerage:
  address: 100 Athens Town Boulevard, Ste 1 Athens, GA 30606
  phone: 706-621-6085
  phone_type:
  phone2:
  phone2_type:
  email: Justin@WoodallRealtyGroup.com
  url: http://WoodallRealtyGroup.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809033';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.myathenshomevalue.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.athensareahomesearch.com/?SRC=Blog

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.myathenshomevalue.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.athensareahomesearch.com/?SRC=Blog

lender:
  show_section: true
  header_text: Preferred Lender
  # headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name: Russell Tanner
  license_number: NMLS 204257
  brand: Prime Lending
  license_number2: License 26027
  phone: 706-621-1704
  email: Tanner@PrimeLending.com
  # url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/woodallrealtygroup/?fref=ts
  linkedin_url: http://www.linkedin.com/pub/justin-woodall/56/371/36a
  gplus_url: https://plus.google.com/114169053669009564939/posts
  youtube_url: https://www.youtube.com/channel/UCzU_pGIpjRotds3pFEN9gTA
  twitter_url: https://twitter.com/justin_woodall
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Woodall-Realty-Group/
  trulia_url: http://www.trulia.com/profile/justin-woodall-agent-athens-ga-zgzbsjgs/overview
  yelp_url: http://www.yelp.com/biz/the-justin-woodall-group-keller-williams-realty-greater-athens-watkinsville
  podcast_url: https://itunes.apple.com/us/podcast/athens-real-estate-podcast/id933361524?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0d2952'
  theme_color: '#bfbfbf'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(13, 41, 82, 1.0)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
