audit_header: false
title: Campbell & Keller Team Real Estate Video Blog
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Campbell & Keller Team - your professional Baltimore & Carroll Counties Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Nick Keller
  license_number:
  about_markdown: |
    Campbell & Kellar Team of Keller Williams Legacy is a fast growing, progressive Real Estate team pioneering evolution of our industry and kicking a dent in the Baltimore metro community and local real estate market.  Our approach is Family Helping Families be strategic in making decisions with clear direction while supporting with strong leadership, communication, expectations, and accountability.

    We use progressive systems & tactics, strategic thinking, and years of experience to help position our clients to have the right information so that they can ultimately make the right decisions.
  market: Baltimore & Carroll Counties
  brand: Campbell & Keller Team
  brokerage:
  address: 1515 Reisterstown Road, 2nd floor<br>Pikesville, MD 21208
  phone: 443-660-9229
  email: Nick@theCKteam.com
  url: www.CampbellandKellarTeam.com
  first_CTA_text: Home Evaluation
  first_CTA_URL: http://www.bestmdhomesearch.com/homevalue/value/?src=vyralâ€‹
  second_CTA_text: Home Search
  second_CTA_URL: http://www.bestmdhomesearch.com/?src=vyral
  VR_form: http://oi.vresp.com?fid=b75e53759f
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/theCKteam/
  linkedin_url: https://www.linkedin.com/in/nick-kellar-b3a33112
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCtNQYKYMqRRtJVLwGppVZPA
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/CKteam/
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: Campbell & Keller Team Real Estate Podcast
  categories: News & Politics
  image:
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Baltimore & Carroll Counties Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Campbell & Keller Team - your professional Baltimore & Carroll Counties Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Baltimore & Carroll Counties, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author:
images:
  client_headshot_path: '/img/headshot.jpg'
  hero_logo_path: '/img/logo.png'
  hero_text: Real Estate Video Blog
  hero_background_hex: '#730709'
  hero_image_path: '/img/background.jpg'
brand_color: '#008AAC'
theme_color: '#000'
theme_text_color: '#fff'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
