audit_header: false
title: Baystate Financial Video Blog with Stephen Cunha
description: 'Stephen Cunha can help you take charge of your financial future by developing a customized strategy to reach your financial goals and further your success.'
show_custom_links: true
custom_links:
  - title: About Us
    url: http://www.retirementcfo.com/about-us
  - title: Personal Financial View
    url: https://wealth.emaplan.com/metbd/SignIn?metbd

client:
  name: Stephen Cunha
  license_number:
  about_markdown: |
    With over 23 years of experience in the financial services industry, Stephen Cunha specializes in helping clients achieve their most cherished goals. Having spent 13 years in the Army Reserve, he draws on his strong leadership background to train and teach clients the fundamentals of financial independence. Stephen thrives in relating the most arcane financial concepts to individuals and business owners, empowering them to better understand the complex world of investing. Throughout his career, he has focused his expertise on creating clarity out of confusion for clients on both the corporate and individual side.
  market:
  brand: Baystate Financial
  brokerage:
  address: 301 Edgewater Place - Suite 200<br>Wakefield, MA 01880
  phone: 781-876-4113
  phone_type:
  phone2:
  phone2_type:
  email: scunha@baystatefinancial.com
  url: http://RetirementCFO.com

Emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809816';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Request A Consultation
  first_CTA_URL: http://www.retirementcfo.com/contact
  second_CTA_text: Request a Plan Proposal
  second_CTA_URL: /

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Let’s Talk"
    CTA_text: "Are you ready to take control of your financial future? If you have any questions about retirement or financial planning, I’m here to help."
    CTA_link_text: "Request a Consultation"
    CTA_url: http://www.retirementcfo.com/contact

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Planning for Retirement"
    CTA_text2: "We can help you retire comfortably and live with confidence."
    CTA_link_text2: "Request a Plan Proposal "
    CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Secure Your Financial Future
  welcome_text_markdown: >
    Stephen Cunha provides individual investors and business owners with custom wealth management and benefit strategies. Whatever you hope to achieve, we seek to advance your goals through all chapters of your life: today, tomorrow, and for years to come.

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url: https://www.linkedin.com/in/stephen-cunha-cfp%C2%AE-aif-crps-clu-cltc-0b2870/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: Baystate Financial Podcast with Stephen Cunha
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Whether you are interested in retirement planning, wealth management, or benefit strategies, Certified Financial Planner™ Stephen Cunha is here with the latest tips.'
  description: 'Stephen Cunha can help you take charge of your financial future by developing a customized strategy to reach your financial goals and further your success.'
  keywords: Stephen Cunha, Financial Planning, Retirement Plans, Retirement Planning, Wealth Management, Financial Advisor, Certified Financial Planner, Benefit Planning, Retirement Plan Management
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  hero_logo_path2: /img/logo2.png
  logo_width_number: 30
  hero_text: Stephen Cunha
  hero_text_2: CFP®, C(k)P, AIF, CRPS®, CLU, CLTC
  hero_text_3: Aspiring to be your
  hero_text_4: "RETIREMENT CFO™"
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#BB9544'
  theme_color: '#1C3C48'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(96, 95, 95, .75)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
