audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Donald Payne
  license_number:
  about_markdown: | 
    Don Payne is a devoted husband, father, son, friend, and volunteer. All of these life experiences make him uniquely qualified to have been the realtor of choice for home buyers and sellers since 1979. The key to Don's success for more than 25 years has been his willingness to take the time to get to know his clients, and to understand how their housing situation can best help them meet their personal visions. Don has used his real estate expertise and relationship-building skills to help people in all walks of life realize their home ownership goals. He has reached out to single individuals, first-time homebuyers, new families, single parents, and well-established homeowners in a broad spectrum of pricing ranges, throughout their desired market areas.

  market:
  brand: Don Payne Group
  brokerage: Vision Realty, Inc
  address: 4608 N. High Street, Columbus, OH 43214
  phone: 614-447-3175
  phone_type: office
  phone2:
  phone2_type:
  email: donaldpayne@visionrealty.com
  url: http://www.visionrealty.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://donaldpayne.boldleads.com/?source=widget
  second_CTA_text: Home Search
  second_CTA_URL: http://www.homeseekcolumbus.com/
  VR_form: http://oi.vresp.com?fid=8d5c8a2162

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://donaldpayne.boldleads.com/?source=widget

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.homeseekcolumbus.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/visionrealtydonpayne/
  linkedin_url: https://www.linkedin.com/in/donaldpaynevisionrealty/
  gplus_url: https://plus.google.com/u/0/b/105325345329864318600/105325345329864318600?_ga=2.5960374.409371348.1511892917-1322499719.1511892917
  youtube_url: https://www.youtube.com/channel/UCBzCBRvaLNuCCDS1C1fVDNA
  twitter_url: https://twitter.com/donaldapayne
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/donpaynepgroup/
  trulia_url: https://www.trulia.com/profile/don-payne-group-agent-43214-oh-zg17j7xl/overview
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#000000'
  theme_color: '#000000'
  accent_color: '#FCE519'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
