audit_header: false
title: -- CLIENT BRAND --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Duke Kimhan
  license_number: Broker License RB-21817
  about_markdown: |
    'When it came to delving into the world of Real Estate, Duke first bought and sold his own properties, then became a Broker himself. He has been a PB at Coldwell Banker in Florida, PB at Realty Experts in HI and Owner/Broker of Condo.Com in HI. His newest challenge is Managing HiPacific Property Management Division with Team Lally. Duke has earned numerous Real Estate Designations: ABR, CRS, CRB, GRI, SRES, CDPE, BPO, and continues to educate himself in all areas of Real Estate to better serve you, his Clients and Friends.'
  market: Hawaii
  brand: HI Pacific Property Management
  brokerage:
  address: '99-209 Moanalua Rd # 305<br>Aiea, HI 96701'
  phone: 808-445-9223
  phone_type:
  phone2:
  phone2_type:
  email: info@HIPacificPM.com
  url: http://HIPacificPM.com

CTAs:
  first_CTA_text: Rent Your Home
  first_CTA_URL: http://www.hipacificpm.com/Guaranteedrent
  second_CTA_text: Home Search
  second_CTA_URL: http://www.hipacificpm.com/faqs
  VR_form: http://oi.vresp.com?fid=bc9bd80877

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "If We Don’t Lease Your Home in 30 Days, We’ll pay the Rent!"
    CTA_text: "If both you and HiPacificPM agree to enter into a Guaranteed Lease agreement, we will also guarantee that the tenant will pay the agreed upon rent for a minimum of 6 months."
    CTA_link_text: "Rent Out Your Home"
    CTA_url: http://www.hipacificpm.com/Guaranteedrent

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Have a Question about the Guaranteed Rent Program?"
    CTA_text2: "Check out these FAQ's from our Clients"
    CTA_link_text2: "Frequently Asked Questions"
    CTA_url2: http://www.hipacificpm.com/faqs

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/HIPacific-Property-Management-1598929470384417
  linkedin_url: https://www.linkedin.com/in/hipacificpm
  gplus_url: https://plus.google.com/b/104259744657557878378/104259744657557878378
  youtube_url: https://www.youtube.com/channel/UCfTHiiR-HtktD1L0hwrBHhA
  twitter_url: https://twitter.com/HipacificPm
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url: http://www.yelp.com/biz/hawaii-pacific-property-management-aiea-2
  podcast_url: https://itunes.apple.com/us/podcast/hawaii-property-management-podcast-with-duke-kimhan/id1218413212?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Hawaii Property Management Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#0b2b44'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: transparent

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
