audit_header: false
title: San Fernando Valley Real Estate Video Blog with Scott Himelstein
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Our Listings
    url: http://www.scottworks4u.com/featured-listings/
  - title: Mortgage Calculator
    url: http://www.scottworks4u.com/mortgage-calculator/
  - title: About
    url: http://www.scottworks4u.com/agent/scott-himelstein/

emma:
  lightbox:
  form:

client:
  name: Scott Himelstein
  title:
  license_number: 'BRE #01452719'
  about_markdown: |
    Scott graduated from the University of San Francisco in 1999 and as a Certified Probate Real Estate Expert, he has both the experience and the knowledge (se habla espanol y se fala portugues) to be the best. Whether you are buying or selling a home in the San Fernando, Santa Clarita, Simi or Conejo Valleys, Scott is the best option for you.

    By doing business with one of the San Fernando Valley's top selling real estate groups, you will benefit from the knowledge and skills of an experienced and dedicated team of professionals working for you. Utilizing the latest technologies, market research, and business strategies, he will work to surpass your expectations. More so, you will be listened to and assisted with solutions that are tailored to your real estate needs.
  market: San Fernando Valley
  brand: Park Regency Real Estate
  brokerage:
  address: 10146 Balboa Blvd. <br>Granada Hills,CA 91344
  phone: 818-396-3311
  phone_type:
  phone2:
  phone2_type:
  email: Scott@ScottWorks4u.com
  url: http://www.scottworks4u.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.whatsyoursocalhomeworth.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.scottworks4u.com/#home-search

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.whatsyoursocalhomeworth.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.scottworks4u.com/#home-search

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/ScottWorks4u
  linkedin_url: http://www.linkedin.com/pub/scott-himelstein/35/408/992
  gplus_url: https://plus.google.com/100282452998972599344
  youtube_url: https://www.youtube.com/channel/UCEOBPWGnfrqskizp4cw0xwQ
  twitter_url: https://twitter.com/scottworks4u
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Scott-Himelstein/
  trulia_url: http://www.trulia.com/profile/Real_Estate_Pro-Porter_Ranch_CA-1443816/
  yelp_url: http://www.yelp.com/biz/scott-himelstein-porter-ranch
  podcast_url: https://itunes.apple.com/us/podcast/san-fernando-valley-real-estate-podcast-scott-himelstein/id915932997?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#ff0000'
  theme_color: '#b3b3b3'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
