audit_header: false
title: The REllis Group
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
  -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Rob Ellis
  license_number: 2014002724
  about_markdown: >-
    The REllis Group is a real estate team based out of Central Ohio with a
    vision to motivate and inspire people to create a better life through real
    estate. Our core commitment is to focus on new business daily, master all
    aspects of the home sales process, deliver a world-class client experience,
    and create raving past clients that continue to work with our team
    throughout their lifetime. The REllis Group services all 8 counties that
    surround Columbus, Ohio.
  market: Columbus
  brand: The REllis Group
  brokerage: Key Realty
  address: '995 Goodale Blvd, 2nd Floor<br>Columbus, OH 43212'
  phone:  614-400-8762
  phone_type:
  phone2:
  phone2_type:
  email: REllisGroup@gmail.com
  url: 'http://REllisGroup.com'

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808338';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.rellisgroup.com/search/criteria/c_39.991851,-83.003082/s_2/z_11'
sidebar_CTA:
  CTA_image_path: /img/cta-images/001.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: 'http://www.rellisgroup.com/search/criteria/s_2'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/REllisGroup/'
  linkedin_url: 'https://www.linkedin.com/in/rellisgroup/'
  gplus_url: 'https://plus.google.com/u/0/b/117154241306022327812/117154241306022327812'
  youtube_url: 'https://www.youtube.com/channel/UCvMgf2ifOnSAHsysQ9keQpg'
  twitter_url: 'https://twitter.com/RellisGroup'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/The-REllis-Group/'
  trulia_url: >-
    https://www.trulia.com/directory/-agent-Rob+Ellis+And+The+REllis+Group+at+Key+Realty/
  yelp_url: 'https://www.yelp.com/biz/rellis-group-at-key-realty-columbus'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/columbus-real-estate-podcast-with-rob-ellis/id1218851836?mt=2
podcast:
  title: Columbus Real Estate Podcast with Rob Ellis
  categories:
    - Education
  image: /img/podcast.png
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /uploads/logos.png
  logo_width_number: 60
  hero_text:
  hero_background_hex: '#ffffff'
  hero_image_path: /uploads/ellis-blog-image-background.png
site_colors:
  brand_color: '#1d5aa3'
  theme_color: '#535353'
  theme_text_color: '#ffffff'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#1d5aa3'
  secondary_button_border_color: '#1d5aa3'
  secondary_button_background_color: '#1d5aa3'
  secondary_button_text_color: '#ffffff'