audit_header: false
title: Stellar Realty Northwest
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title: Featured Listings
    url: http://www.portlandpropertyfinders.com/results/?OfficeMLS=SRNW01
  - title: Finance
    url: http://www.portlandpropertyfinders.com/finance/
  - title: Agents
    url: http://www.portlandpropertyfinders.com/agents/

client:
  name: Scott Besaw and Paul Campbell
  license_number:
  about_markdown: |
    Since opening its doors in 2009, Stellar Realty Northwest has done $39.5 million dollars in sales volume and over 175 transactions. Over the years, Scott Besaw and Paul Campbell have helped facilitate a wide range of real estate sales including bank-owned, short sales, bare land, condos, and luxury homes. In order to accommodate the team's vast experience with a variety of real estate endeavors, our office is centrally located in order to best serve all of Portland and its surrounding areas.
    <br><br>
    Along with a team that includes agents with over 40 years of combined experience and a full-time office support staff, Stellar Realty Northwest has helped hundreds of buyers and sellers reach their real-estate goals. Their unique team approach, combined with industry leading technology, has allowed them to provide an experience for their clients that is unparalleled in the industry.
  market: Portland
  brand: Stellar Realty Northwest
  brokerage:
  address: 5530 SW Kelly Ave<br>Portland, OR 97239
  phone: 503-265-8153
  phone_type:
  phone2:
  phone2_type:
  email: Info@StellarNW.com
  url: http://PortlandPropertyFinders.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.portlandpropertyfinders.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.portlandpropertyfinders.com/results/
  VR_form: http://oi.vresp.com?fid=34a3742877

sidebar_CTA:
  CTA_image_path: /img/cta-images/005.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: http://www.portlandpropertyfinders.com/results/

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/StellarNW
  linkedin_url: https://www.linkedin.com/in/creativerealestate/
  gplus_url: https://plus.google.com/107133429372194274830
  youtube_url: https://www.youtube.com/channel/UCykMXJs4T54IpKTQX8Gn5KA
  twitter_url: https://twitter.com/Stellarrealtynw
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Stellar-RealtyNW/
  trulia_url: http://www.trulia.com/profile/scottbesaw/
  yelp_url: http://www.yelp.com/biz/stellar-realty-northwest-portland-2
  podcast_url: https://itunes.apple.com/us/podcast/stellar-realty-real-estate-podcast/id1218031320?mt=2

podcast:
  title: Stellar Realty Real Estate Podcast
  categories: Education
  image: http://stellarrealtyblog.com/img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Stellar Realty Northwest
  hero_background_hex: '#000'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#8bba33'
  theme_color: '#000'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#8bba33'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
