audit_header: false
title: JR Rouse with Sotheby's International Realty
description: 'J.R. Rouse of Sotheby's International Realty Intention / Goal is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, I provide you the answer to  any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.  - With Appreciation J.R. Rouse, Broker Associate'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  license_number:
  about_markdown: |

  market:
  brand: JR Rouse with Sotheby's International Realty
  brokerage: Sotheby's International Realty
  address: 574 Lighthouse Ave, Pacific Grove, CA 93950
  phone: 831-277-3464
  phone_type:
  phone2:
  phone2_type:
  email: jr@jrrouse.com
  url: http://jrrouse.com/

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://jrrouse.com/MarketAnalysis
  second_CTA_text: Home Search
  second_CTA_URL: http://jrrouse.com/OnlineSearchRequest2?operation=show_search&ls=REIL&county=MONTEREY%20CA
  VR_form: http://oi.vresp.com?fid=a258ef5749

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://jrrouse.com/MarketAnalysis

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://jrrouse.com/OnlineSearchRequest2?operation=show_search&ls=REIL&county=MONTEREY%20CA

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    J.R. Rouse of Sotheby's International Realty Intention / Goal is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, I provide you the answer to  any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.  - With Appreciation J.R. Rouse, Broker Associate

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url: https://www.linkedin.com/in/john-j-r-rouse-6278161/
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/jrrouse
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/JR-Rouse/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with JR Rouse'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'JR Rouse'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#002a5c'
  theme_color: '#2c2c2c'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
