audit_header: false
title: The Dixon Group
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
  -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Daniel Dixon
  license_number:
  about_markdown: >-
    Daniel Dixon is a seasoned Licensed Real Estate Broker, Investor, and
    Business Owner based in Highlands Ranch, Colorado. As a proud Colorado
    resident, he possesses the area and marketplace knowledge necessary to
    provide a pleasant, hassle-free transaction every single time. Furthermore,
    Daniel offers his extensive expertise in internet lead generation and
    internet marketing during the entire selling, listing, or investing process.



    Throughout his career, Daniel has consistently doubled his realty business
    each year. Within just three yearsâ€™ time, he has successfully sold 130+
    homes and made over $40 million in home sales. Recently, Daniel expanded his
    business to South Florida. Ultimately, he strives to have real estate teams
    in all major markets countrywide who are success-driven and infinitely
    dedicated.



    Both hardworking and equally as driven, Daniel is 110% committed to going
    the extra mile from list to close and beyond for each client he represents.



    During his free time, Daniel enjoys playing football and spending quality
    time with his lovely wife and children.&nbsp;



    Whether you are a first time home buyer, would like to effectively sell or
    invest in a property, or are looking for your dream home, Daniel Dixon is
    here to make all of your real estate goals a reality. Feel free to contact
    him with your inquiries.&nbsp;
  market: Denver
  brand: The Dixon Group
  brokerage: Keller Williams
  address: '50 South Steele St., Suite 700<br>Denver, Colorado, 80209'
  phone: 303-506-7106
  phone_type:
  phone2:
  phone2_type:
  email: DixonGroup@kw.com
  url: 'http://www.metrodenverliving.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'https://www.metrodenverliving.com/home-valuation/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.metrodenverliving.com/'
  phone_CTA: true
  VR_form: 'http://oi.vresp.com?fid=54c1fba023'
sidebar_CTA:
  CTA_image_path: /img/cta-images/001.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: /homesearch/
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/dixonsoldit/'
  linkedin_url: 'https://www.linkedin.com/in/daniel-j-dixon-33158255/'
  gplus_url: >-
    https://plus.google.com/b/106028982563820783435/+DanielDixonKellerWilliamsRealtyDenver
  youtube_url: 'https://www.youtube.com/channel/UCYE6kKfeC86aKzjrBB-zF6w'
  twitter_url: 'https://twitter.com/dixonsoldit'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Dixon-Group/'
  trulia_url: >-
    https://www.trulia.com/profile/the-dixon-group-agent-denver-co-zg5jqmwx/overview
  yelp_url: 'https://www.yelp.com/user_details?userid=4xmvSIjeqr63rXfdZPPg2w'
  podcast_url: >-
    https://itunes.apple.com/us/podcast/denver-real-estate-podcast-with-daniel-dixon/id1213997609?mt=2
podcast:
  title: Denver Real Estate Podcast with The Dixon Group
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: Real Estate Video Blog
  hero_background_hex: '#8b8a8f'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#c6202e'
  theme_color: '#000000'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0.7)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 15
  button_padding_height_number: 10
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#c6202e'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'