audit_header: false
title: Northern Nevada Real Estate Video Blog with Rick Canale
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Rick Canale
  license_number:
  about_markdown: |
    As a professional REALTOR® in Northern Nevada since 2001 and a real estate investor, I am committed to providing you with excellent customer service through a warm, friendly, and honest relationship.

    I have three simple goals. (1) To represent my clients professionally and competently, (2) To ensure that your experience with me is pleasant, and (3) to work diligently for you. My market plan includes aggressive sales techniques and the use of the internet. I have lived in Northern Nevada for over 35 years and raised my family here. I believe this is an ideal place to live because of what the area has offers.

    My appreciation for this area deepens daily because there is so much to enjoy here. The history, seasonal changes, majestic mountains, fragrant pines, open valleys, pristine lakes, and flowing rivers are just a few of the reasons. The vitality of the people, the proximity to world-class ski resorts and Lake Tahoe, and the recreational opportunities available certainly make it a fantastic place to live.

    Quality of life is important, and I have found it here.
  market: Northern Nevada
  brand:
  brokerage: Keller Williams Group One Inc.
  address: 10539 Professional Circle<br>Ste 100, Reno, NV 89521
  phone: 775-301-1312
  phone_type: Direct
  phone2: 775-823-8787
  phone2_type: Office
  email: Rick@NorthernNevadaHouseHunters.com
  url: https://www.northernnevadahousehunters.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.northernnevadahousehunters.com/selling/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.northernnevadahousehunters.com/search/advanced_search/
emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808882';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.northernnevadahousehunters.com/selling/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.northernnevadahousehunters.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Rick Canale's mission is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/RickCanaleRE/
  linkedin_url: https://www.linkedin.com/in/rcanale/
  gplus_url:
  youtube_url: https://www.youtube.com/channel/UCYa-OhNINSae0QBdCr1QZeg
  twitter_url: https://twitter.com/Rick_Canale
  instagram_url: https://www.instagram.com/rcan74/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog with Rick Canale
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0,0,0,.65)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
