audit_header: false
title: '-- CLIENT BRAND --'
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Valerie Van de Zilver
  license_number:
  about_markdown: >-
    Currently the owner of The Zilver Realty Group as well as Valerie’s Vacation
    Homes, Valerie dedicates her time to both helping buyers and sellers, and
    managing forty-plus vacation homes in Orange County, CA. Maintaining
    a sincere devotion and respect for her clients, Valerie’s network of lenders,
    buyers and sellers is predominantly by referral and a client-base whom have
    been with her since she began.<br><br>

    With over three decades of Mortgage Lending and Real Estate experience,
    Valerie Van de Zilver has built a career on matching her clients with that
    perfect home and that unmatched connection as soon as they walk in the door.
  market:
  brand: Zilver Realty Group
  brokerage:
  address: '13951 Carroll Way #E<br>Tustin, CA 92780'
  phone: 714-334-9156
  phone_type:
  phone2:
  phone2_type:
  email: valerie@valeriev.com
  url: 'http://www.zilverrealtygroup.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.zilverrealtygroup.com/what-is-my-home-worth/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.zilverrealtygroup.com/property-search/'
  VR_form: 'http://oi.vresp.com?fid=773dab1052'
sidebar_CTA:
  CTA_image_path: /img/cta-images/004.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: 'http://www.zilverrealtygroup.com/property-search/'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/zilverrealtygroup/'
  linkedin_url: 'https://www.linkedin.com/in/valerie-van-de-zilver-8258324'
  gplus_url: 'https://plus.google.com/b/111643801975202317457'
  youtube_url: 'https://www.youtube.com/channel/UCEDByOnNZ8Yor0UQ1ySlcwA'
  twitter_url: 'https://twitter.com/ValerieV'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Valerie4Homes/'
  trulia_url: 'https://www.trulia.com/profile/valerie-van-de-zilver-agent-tustin-ca-zgywvss2/reviews'
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/orange-county-real-estate-podcast-valerie-van-zilver/id1254489145?mt=2
podcast:
  title: Orange County Real Estate Podcast with Valerie Van de Zilver
  categories: Education
  image: 'http://i.imgur.com/zYnv3zR.jpg'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /uploads/valerie-headshot.jpg
  hero_logo_path: /img/zilver_logo.png
  logo_width_number: 30
  hero_text: Real Estate Video Blog
  hero_background_hex: '#353535'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#e16720'
  theme_color: '#57c3b7'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 0px
  shadow_color: '#ffffff'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#57c3b7'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'