audit_header: false
title: Albany Real Estate Video Blog with Kevin Clancy
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Our Listings
    url: http://www.clancyrealestate.com/custompages_reports.php?key=our_listings
  - title: Our Team
    url: http://www.clancyrealestate.com/custompages_reports/team_clancy.htm
  - title: About
    url: http://www.clancyrealestate.com/custompages_reports/about.htm

client:
  name: Kevin Clancy
  title:
  license_number:
  about_markdown: |
    Kevin Clancy is the #1 Realtor in the Capital Region as voted by the Times Union Readers "best of" poll. He has been providing real estate brokerage and appraisal services to the Capital District for over 25 years. He is a New York State licensed real estate broker, Insurance broker, and general certified appraiser. Kevin is a HUD approved broker and started his career specializing in the sale of HUD homes. Kevin's appraisal experience ranges from vacant land and single family homes to multi-tenant office buildings and retail centers.

    A graduate of Siena College with a degree in marketing, Kevin obtained an MBA from the University at Albany in the Spring of 2005. A portion of this degree requirement included an in-depth research paper on residential real estate in the Capital Region. During his career Kevin spent several years evaluating residential and commercial real estate throughout the northeast. This includes more then an estimated 10,000 residential homes in the Capital District. This is more homes than a typical Realtor will evaluate in an entire career! For a thorough evaluation of your home prior to listing, Kevin's experience speaks for itself. Kevin's past experience makes him the perfect choice to meet any of your Capital Region or Albany Area real estate sales or appraisal needs. Services include full service and discount brokerage, appraisals, property management, and general consultation services.
  market: Albany
  brand: Clancy Real Estate
  brokerage:
  address: 1 Fletcher Road<br>Albany, New York 12203
  phone: 518-861-7016
  phone_type:
  phone2:
  phone2_type:
  email: Kevin@ClancyRealEstate.com
  url: http://ClancyRealEstate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.albanynyhomevalues.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.albanyhomefinder.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.albanynyhomevalues.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.albanyhomefinder.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Clancy-Real-Estate/53079920567
  linkedin_url: https://www.linkedin.com/in/albanynyrealestate
  gplus_url: https://plus.google.com/u/0/111744138545569514418/
  youtube_url: https://www.youtube.com/channel/UCfdkq316BAtmSHrYxDNlDdA
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/KevinClancy/
  trulia_url: http://www.trulia.com/profile/kevin-clancy-1-voted-realtor-agent-albany-ny-221545/
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#22933e'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0, 0, 0, .8)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
