audit_header: false
title: Chicago Real Estate Video Blog with Ashley Carter
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: The Carter Property Group
  license_number:
  about_markdown: >-
    The Carter Property Group consists of a team of experienced sales, marketing
    & transactional specialists that assist our clients through one of the
    biggest transitions in their lives, the purchase or sale of their home.

    <br>

    <br>The Carter Property Group is in the Top 1% of all the real estate agents
    in Chicago Association of Realtors.
  market: Chicago
  brand: Carter Property Group
  brokerage: Keller Williams Preferred Realty
  address: '939 W. North Ave, Suite 750 Chicago, IL 60642'
  phone: 773-551-8808
  phone_type:
  phone2:
  phone2_type:
  email: info@CarterPropertyGroup.com
  url: 'http://www.CarterPropertyGroup.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://www.carterpropertygroup.com'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://www.carterpropertygroup.com/sell.php'
  phone_CTA: true
  VR_form:
sidebar_CTA:
  CTA_image_path: /img/cta-images/006.jpg
  CTA_title: Looking to Buy a Home?
  CTA_text: Search the entire MLS for homes located in -- MARKET --.
  CTA_link_text: Home Search Tool
  CTA_url: 'http://www.carterpropertygroup.com/sell.php'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/CarterPropertyGroup'
  linkedin_url: 'https://www.linkedin.com/in/ashleycarter'
  gplus_url: 'https://plus.google.com/+Carterpropertygroup'
  youtube_url:
  twitter_url: 'https://twitter.com/ashleypcarter'
  instagram_url:
  pinterest_url:
  zillow_url: 'http://www.zillow.com/profile/Ashley-Carter/'
  trulia_url: 'https://www.trulia.com/profile/ashley-carter-agent-chicago-il-zgg19f8f/overview'
  yelp_url: 'https://www.yelp.com/biz/carter-property-group-chicago'
  podcast_url:
podcast:
  title: Chicago Real Estate Podcast with Ashley Carter
  categories:
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50rem
  hero_text: Real Estate Video Blog
  hero_background_hex: '#b22025'
  hero_image_path: /img/background.jpg
site_colors:
  brand_color: '#020202'
  theme_color: '#050505'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 2px
  shadow_color: '#000000'
buttons:
  button_radius_number: 0
  button_padding_width_number: 20
  button_padding_height_number: 20
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#000000'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: '#000000'
  secondary_button_text_color: '#ffffff'