audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Featured Listings
    url: http://search.bradkorb.com/idx/featured
  - title: Meet The Korb team
    url: http://www.bradkorb.com/staff.php

client:
  name: Brad Korb
  license_number: 'BRE # 00698730'
  about_markdown: |
        As one of the premier real estate businesses in the LA area, Brad Korb's real estate team is unmatched in their level of commitment and tireless devotion they provide to their clients. For over three decades, he has helped his clients visualize and obtain their goals of
        buying or selling a home. He sits down and listens to their unique needs and desires, then puts together the best strategies for achieving the results they want.  Having participated in every aspect of the real estate process over the years, he knows where to center his
        attention in order to bring about success.Brad surrounds himself with a team of professionals who each handle various tasks that need attention, giving him the freedom to focus directly on your transaction. With years of experience with buyers and sellers in the Burbank
        community, Brad is an unparalleled resource for everything from Burbankâ€™s real estate market to community services.  So when your family is ready to move in the Glendale, Burbank , Sun Valley, North Hollywood and surrounding areas in the San Fernando Valley, contact the
        professional who is Focused on What Matters to You.
  market: Burbank
  brand: The Brad Korb Real Estate Group
  brokerage:
  address: 3813 W. Magnolia Blvd.<br>Burbank, CA 91505
  phone: 818-953-5300
  phone_type:
  phone2:
  phone2_type:
  email: brad@bradkorb.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.bradkorb.com/form-cma.php
  second_CTA_text: Home Search
  second_CTA_URL: http://www.bradkorb.com/buyers.php
  VR_form: http://oi.vresp.com?fid=ff56bf12e2

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: http://www.bradkorb.com/buyers.php

lender:
  show_section: True
  header_text: Meet My Trusted Lender
  headshot_path: /img/lender.jpg
  logo_path:
  logo_path_2:
  name: Brian McKim<br>Sales Manager | NMLS# 381742
  brand: Skyline Home Loans
  phone: 818-844-8207 Office<br>818-421-4737 Cell<br>818-484-2014 Fax
  email: bmckim@skylinehomeloans.com
  url:
  address: 505 North Brand Blvd. 15th Fl<br>Glendale, CA 91203

welcome_box:
  welcome_headline: Sign up for our -- MARKET -- Newsletter
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheBradKorbRealEstateGroup
  linkedin_url: http://www.linkedin.com/in/bradkorb/
  gplus_url: https://plus.google.com/u/0/+BradKorb/about
  youtube_url: https://www.youtube.com/channel/UCiJwvniUev3k1C6rqTEvscQ
  twitter_url: https://twitter.com/bradkorb
  instagram_url: https://www.instagram.com/bradkorbrealestategroup/
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Brad-Korb/
  trulia_url: http://www.trulia.com/profile/brad-korb-agent-burbank-ca-77679
  yelp_url: http://www.yelp.com/biz/the-brad-korb-team-burbank
  podcast_url: https://itunes.apple.com/us/podcast/burbank-real-estate-podcast-with-brad-korb/id1225767403?mt=2

podcast:
  title: Burbank Real Estate Podcast with Brad Korb
  categories: Education
  image: http://lasells.com/img/podcast.png
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: L.A. Real Estate Video Blog
  hero_background_hex: '#034275'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#D2121D'
  theme_color: '#034275'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#034275'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
