audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

emma_form:

client:
  name: Michael Adams
  license_number:
  about_markdown: |
    With a wealth of experience under our belts (buying and selling homes), our team and network of real estate experts have handled some of the most complicated real estate transactions on the market today. Whether you're facing foreclosure, have an inherited property that you don't know what to do with, or simply want to sell your home because you're ready for the next chapter of your life, we will handle your transaction with the utmost professionalism and care.
  market:
  brand: Brevard Buyers Group LLC
  brokerage:
  address: 7058 Red Bay Ct. Melbourne Fl. 32940
  phone: 321-652-1656
  phone_type:
  phone2:
  phone2_type:
  email: oakhavengroupllc@gmail.com
  url: http://www.webuyhousesinbrevard.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.webuyhousesinbrevard.com/170029
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.webuyhousesinbrevard.com/170029

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheOakHavenGroupLLC/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url: https://twitter.com/OakHavenGroup
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#295F84'
  theme_color: '#00A99D'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
