audit_header: false
title: '-- CLIENT BRAND --'
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: About
    url: /about
client:
  name: 'Philipp Fries & Michele Dupree'
  license_number:
  about_markdown: >-
    As a team, we work hard to incorporate all our daily life values into our
    everyday work ethic at every turn; our number one goal is to help our clients
    find their happiness. We guarantee that we will do everything in our power to
    provide you, our clients, with the utmost of professional service, whether
    that be through the timely follow up of all phone correspondence, our
    flexibility, or our ability to provide you with as much information as
    possible when it comes to your new real estate venture. We take extreme pride
    and pleasure in both helping our clients realize their dreams by helping them
    to embark on the next step in their lives in their new homes. To us, there is
    nothing more rewarding!





    Please feel free to reach out to us with any of your real estate questions or
    concerns. We are more than pleased to help!
  market: Tampa Bay Area
  brand: 'Fries & Dupree Real Estate Consultants'
  brokerage: Keller Williams Realty
  address: '3502 Henderson Blvd Ste 300<br>Tampa, FL 33609'
  phone: 813-447-2991
  phone_type:
  phone2:
  phone2_type:
  email: PFriesKW@gmail.com
  url: 'http://www.FriesandDupree.com'
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://friesanddupree.kwrealty.com/sell/'
  second_CTA_text: Home Search
  second_CTA_URL: 'http://friesanddupree.kwrealty.com/map/'
  VR_form: 'http://oi.vresp.com?fid=52a8a07d77'
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: 'http://friesanddupree.com/basic-search/'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/FriesandDupreeRealEstate/'
  linkedin_url: 'https://www.linkedin.com/in/philippfries/'
  gplus_url: 'https://plus.google.com/118342146562281930945'
  youtube_url: 'https://www.youtube.com/channel/UCG2VZucKdlzMsSGmBCPex4g'
  twitter_url: 'https://twitter.com/philippfries'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Philipp-Fries-PA/'
  trulia_url: 'https://www.trulia.com/profile/philipp-fries-agent-tampa-fl-zgfd2hyf/overview'
  yelp_url:
  podcast_url:
podcast:
  title: Tampa Bay Area Real Estate Podcast with Philipp Fries
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /uploads/fries-and-dupree-headshot.png
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text:
  hero_background_hex: '#333333'
  hero_image_path: /uploads/fries-bkg-brighter.png
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b52f26'
  theme_color: '#333333'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 3px
  shadow_spread: 7px
  shadow_color: '#999999'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'