audit_header: false
title: Alex Lam Personal Real Estate Corporation
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Alex Lam - your professional Royal Pacific Realty Real Estate Agent.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Alex Lam<br>Personal Real Estate Corporation
  license_number:
  about_markdown: |
    Over my past 10 years in Real Estate I have honed my skills to best serve you best. After graduating from Simon Fraser University with a BA in Psychology, I have worked as an Mortgage Broker, Life Insurance Sales, Mutual Funds Representative, and even as an Optician. Let Alex's personal network of over 2000 professionals aid you in your real estate needs.

    Whether you are selling your home, looking for a new home or buying an investment property, Alex will expertly navigate you through the complexities of the real estate process. That is because Alex is not just a real estate agent; he is a researcher, an analyst, an advisor, a marketer, a negotiator and if needed a Psychologist. He is also a trusted friend you can rely on and who will put your needs first. He has become friends with many of his past clients.
  market:
  brand: Royal Pacific Realty
  brokerage: 
  address: 550 650 W 41st Ave, Vancouver, BC V5Z 2M9
  phone: 778-898-2539
  phone_type:
  phone2:
  phone2_type:
  email: alexlam@royalpacific.com
  url: http://www.alexlam.net

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809710';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://alexlam.net/home-evaluation.html
  second_CTA_text: Home Search
  second_CTA_URL: http://alexlam.net/vow.html#!/wps/-/noframe~true/recip/30044/idx.search?

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free -- MARKET -- Home Value Report"
    CTA_url: http://alexlam.net/home-evaluation.html

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://alexlam.net/vow.html#!/wps/-/noframe~true/recip/30044/idx.search?
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Get Educated About Real Estate
  welcome_text_markdown: >
    My mission at Vancouver Real Estate Videos is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, my team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/Alexlam.realtor/
  linkedin_url: https://www.linkedin.com/in/alex-lam-6b10214/
  gplus_url: https://plus.google.com/u/0/109904443537825891565
  youtube_url: https://www.youtube.com/channel/UCPXb9c_dyeEIRd3KlDWsUvw
  twitter_url: https://twitter.com/Alex_Lam_yvr
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/alex-lam-royal-pacific-realty-podcast/id1266041450?mt=2

podcast:
  title: Alex Lam Royal Pacific Realty Podcast
  categories: Education
  image: http://i.imgur.com/lmaE3Us.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Alex Lam - your professional Royal Pacific Realty Real Estate Agent.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in vancouver, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Alex Lam'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: 
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#922c46'
  theme_color: '#231f20'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
