audit_header: false
title: -- CLIENT BRAND --
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Kwaku Mitchell
  license_number:
  about_markdown: |
    Through our consultative approach, we will first identify your family's unique needs and desired outcome. From here, you can lean on our team to set expectations, answer questions, prepare you, and lead you through the entire home selling and buying process. What can sometimes seem confusing, stressful, and frustrating, with great communication our team is excited to make the entire process smooth so your family can focus on their next steps.
  market: Orlando
  brand: K Mitchell Team
  brokerage: Keller Williams
  address: 6900 Turkey Lake Rd<br>Suite 1-3, Orlando, FL 32819
  phone: 407-353-7706
  phone_type:
  phone2:
  phone2_type:
  email: Kwaku@KMitchellTeam.com
  url: http://KMitchellTeam.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://kmitchellteam.com/home_value
  second_CTA_text: Home Search
  second_CTA_URL: http://kmitchellteam.com/search#?q_limit=36&q_prioritize=agents.0.id=261203407|office.id=56128&mlsId=28&q_sort=createdAt-&q_offset=0

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808831';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Whatâ€™s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://kmitchellteam.com/home_value

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://kmitchellteam.com/search#?q_limit=36&q_prioritize=agents.0.id=261203407|office.id=56128&mlsId=28&q_sort=createdAt-&q_offset=0

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/kmitchellteam/
  linkedin_url: https://www.linkedin.com/in/kwakumitchell/
  gplus_url: https://plus.google.com/u/0/+KwakuMitchell
  youtube_url: http://www.youtube.com/channel/UCo79D_weNKl-8XLrfxONsSg
  twitter_url: https://twitter.com/KwakuMitchell
  instagram_url: http://instagram.com/kwakumitchell/
  pinterest_url: http://www.pinterest.com/kwakumitchell/
  zillow_url: https://www.zillow.com/profile/Kwaku-Mitchell/
  trulia_url: https://www.trulia.com/profile/kwaku-mitchell-agent-orlando-fl-zg7hvxy8/overview
  yelp_url: http://www.yelp.com/biz/k-mitchell-team-keller-williams-orlando
  podcast_url: https://itunes.apple.com/us/podcast/orlando-real-estate-podcast-with-kwaku-mitchell/id1330724426?mt=2

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0f2541'
  theme_color: '#727272'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(15, 37, 65, .6)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
