audit_header: false
title: Greater Property Group Calgary Real Estate Video Blog
description: If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from the Greater Calgary Group - your professional Calgary Real Estate Agents.
show_custom_links: true
custom_links:
  - title: Featured Listings
    url: http://www.searchcalgaryhomelistings.com/featured
client:
  name:
  license_number:
  about_markdown: |
    The Greater Calgary Group with Re/Max First is a boutique real estate firm comprised of premier real estate professionals working together to serve Calgary and Area.  We offer the best of both world's - the power of an international brand and personalized service of a boutique office.

    Our goal is to provided our local and international clients with exceptional, personalized service, while remaining flexible and innovative so we can thrive in any economic cycle.  Our team provides the tools needed to achieve prominence in the marketplace through education, technology, and training.
  market:
  brand: Greater Property Group Calgary
  brokerage: RE/MAX First
  address: 8820 Blackfoot Trail SE Unit 115<br>Calgary, AB T2J 3J1
  phone: 403-818-9611
  phone_type:
  phone2:
  phone2_type:
  email: info@greaterpropertygroup.com
  url: greaterpropertygroup.com/calgary
  first_CTA_text: Home Evaluation
  first_CTA_URL: http://www.greaterpropertygroup.com/cma-calgary.php
  second_CTA_text: Home Search
  second_CTA_URL: http://www.greaterpropertygroup.com/idx/?feed=creb&search_location=
  phone_CTA: true
  VR_form: http://oi.vresp.com?fid=fc52d51b70
welcome_headline: Get Educated About Real Estate
welcome_text_markdown: |
  Our mission at the Greater Property Group Calgary is to be your best resource for real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. Subscribe to this blog to get the latest news on local market trends and receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/GreaterCalgaryGroup/?fref=ts
  linkedin_url: https://www.linkedin.com/company/the-greater-calgary-group-at-remax-first?trk=biz-companies-cym
  gplus_url: https://plus.google.com/u/0/b/115640214646472043359/115640214646472043359/about?_ga=1.96115925.859963669.1470700688
  youtube_url: https://www.youtube.com/channel/UCGVb90uFiLPbTQ6_DS5K-kQ
  twitter_url: https://twitter.com/GCG_Marketing
  instagram_url: https://www.instagram.com/greatercalgarygroup/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/greater-calgary-group-real-estate-podcast/id1193247036?mt=2
podcast:
  title: Greater Property Group Calgary - Real Estate Podcast
  categories: News & Politics
  image: '/img/podcast.png'
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Greater Calgary Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from the Greater Property Group Calgary - your professional Calgary Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Calgary, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: Greater Property Group Calgary
images:
  client_headshot_path: '/img/headshot.png'
  hero_logo_path: '/img/logo.png'
  hero_text:
  hero_background_hex: '#00A3DA'
  hero_image_path: '/img/background.png'
brand_color: '#00A3DA'
theme_color: '#00A3DA'
theme_text_color: '#353535'
main_body_color: '#ffffff'
main_body_text_color: '#353535'
