audit_header: false
title: Boise Real Estate Video Blog with Graham MacKenzie
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Graham MacKenzie
  license_number:
  about_markdown: |
    Graham moved to the Boise area in the early 90’s to enjoy the amazing outdoor opportunities Idaho has to offer. 13 years ago he traded being a full time fly fishing guide to being a full time real estate agent. His guiding expertise and goal of building lifelong relationships translated very quickly into helping people buy, sell, and invest in real estate; and earning him title of “Rookie of the Year”. He hasn’t looked back. His passion for learning, personal growth, building relationships and adding value to people’s lives have helped his clients get top dollar for their homes, and often win out in hot markets on multiple offers. When he isn’t helping you with real estate you will find him fly fishing a local river or covering endless miles running the local trails. We secretly think he would never come inside if it wasn’t for real estate. Ask him for a fly casting lesson or pick his brain on local trails as part of the package.
  market: Boise
  brand: Ridge to Rivers Realty
  brokerage: Keller Williams Realty Boise
  address: 1065 S. Allante Place Boise<br>Idaho, 83709
  phone: 208-991-4771
  phone_type:
  phone2:
  phone2_type:
  email: Graham@R2RRealty.com
  url: http://r2rrealty.com
  name2: BriAnne
  about_markdown2: |
    BriAnne is from a small town just outside of Idaho Falls, Idaho. She grew up loving the simple things in life. She met her husband in high school, moved to the “Big City", Boise to attend Boise State University. In the early 2000’s, while her husband was building his career in location sound, they moved to 4 different states. In 2007, they bought their first home in Salt Lake City, Utah. A year or so after the market crash they became accidental landlords creating an accidental love for real estate. Shortly there after, BriAnne started a real estate career at Keller Williams Reatly Portland Central. About 6-8 months into her real estate career in Portland “LIFE” happened when their son became very ill which lead them to move back home to Boise, Idaho.

    In early 2014, BriAnne re-launched her career in real estate at Keller Williams Realty Boise. Shortly after she met her team lead, Graham MacKenzie and the rest is history.

    BriAnne is grateful for the opportunities to help families through real estate. She is also grateful for the opportunity to be a mother of two kids. "My kids and husband inspire me to be the best person I can be every day. Also, my parents, siblings, friends and clients have been an incredible influence in my life and I am forever appreciative of them. We as a family love to be outside with friends/family walking, talking, hiking, camping, eating, rolling down hills in all seasons, sledding, snowboarding, and the list goes on….”
emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808596';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.r2rrealty.com/home_valuation
  second_CTA_text: Home Search
  second_CTA_URL: http://www.r2rrealty.com/property

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.r2rrealty.com/home_valuation

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.r2rrealty.com/property

lender:
  show_section: true
  header_text: Buyer's Agent
  headshot_path: /img/headshot2.jpg
  # logo_path: /img/logo.png
  # logo_path_2:
  name: BriAnne
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com
  about:
    BriAnne is from a small town just outside of Idaho Falls, Idaho. In early 2014, BriAnne joined her team lead, Graham MacKenzie. She is grateful for the opportunities to help families through real estate at Keller Williams Realty Boise.

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/R2Rrealty/
  linkedin_url: https://www.linkedin.com/in/gomackenzie
  gplus_url: https://plus.google.com/109216837435619222231
  youtube_url: https://www.youtube.com/channel/UCChgEdMe83rBh7IbEWgbq3w?
  twitter_url: https://twitter.com/gmackenzie23
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/graham25/
  trulia_url: https://www.trulia.com/profile/graham-mackenzie-agent-boise-id-zgjv33k8/overview
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  client_headshot_path2: /img/headshot2.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#699941'
  theme_color: '#0072bc'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgb(86, 107, 120)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
