audit_header: false
title: San Antonio Real Estate Video Blog with Alexis Weigand
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Alexis Weigand
  license_number:
  about_markdown: |
    Alexis Weigand is an experienced, highly driven real estate broker of over 12 years who has managed countless transactions for both domestic and international clients. She is passionate and dedicated in providing her clients the highest level of customer service and personal attention. Let Alexis and her team of professionals guide you through the beautiful Texas Hill Country and assist you in your transaction; whether it’s selling or buying your luxury dream home, your first home or investing in real estate.
  market: San Antonio
  brand: Alexis Weigand Real Estate Group
  brokerage: Keller Williams Luxury
  address: '1018 River Road Suite #300, Boerne, Texas 78006'
  phone: 210-987-8801
  phone_type: office
  phone2: 210-987-8803
  phone2_type: direct
  email: Alexis@AlexisWeigand.com
  url: https://www.WeigandRealEstate.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: https://www.weigandrealestate.com/home-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.weigandrealestate.com/results-gallery/?sort=importdate&status=A&proptype=FM,PH,MF,VT,C,SF,VC

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808997';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

sidebar_CTA:
  - CTA_image_path: /img/cta-images/005.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: https://www.weigandrealestate.com/home-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/004.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.weigandrealestate.com/results-gallery/?sort=importdate&status=A&proptype=FM,PH,MF,VT,C,SF,VC

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Alexis-Weigand-KW-Luxury-Realtor/199758006761600?ref=hl
  linkedin_url: http://www.linkedin.com/in/alexisweigand
  gplus_url: https://plus.google.com/u/0/b/116688734048635986759/dashboard/overview
  youtube_url:
  twitter_url: https://twitter.com/boernetxrealtor
  instagram_url: http://instagram.com/alexisweigandrealestate
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/Alexis-Weigand/
  trulia_url: https://www.trulia.com/profile/alexis-weigand-agent-boerne-tx-zglgyw5m/overview
  yelp_url: https://www.yelp.com/biz/alexis-weigand-group-keller-williams-boerne
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#2a3e99'
  theme_color: '#7b7b7b'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 2px
  w_shadow: 5px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
