audit_header: false
title: Success Mortgage Partners Inc. Video Blog with Kristin Jamieson
description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- Mortgage and Loan advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Compliance
    url: http://www.successmortgagepartners.com/smp-compliance
  - title: Mortgage Mapp App
    url: http://kristin.mortgagemapp.com/

client:
  name: Kristin Jamieson
  license_number: 'NMLS #1097663'
  about_markdown: |
    Success Mortgage Partners, Inc. is dedicated to the highest levels of customer service. We take mortgage compliance seriously.

    Consumers wishing to file a complaint with Success Mortgage Partners, Inc. regarding their experience may complete the Consumer Complaint form and submit electronically. Complaints will be acknowledged by our Complaint Resolution Officer within 10-15 business days, however some may take longer due to the nature of the complaint.
  market:
  brand: Success Mortgage Partners
  license_number2: 'NMLS #130562'
  brokerage:
  address: '16903 Lakeside Dr. Unit #6<br>Montverde, FL 34756'
  phone: 352-242-1535
  phone_type:
  phone2:
  phone2_type:
  email: Kristin@KristinJamiesonFL.com
  url: http://www.SuccessMortgagePartners.com/Kristin

CTAs:
  first_CTA_text: Agent Mastermind
  first_CTA_URL: http://agentmastermind.com/kristinjamieson/
  second_CTA_text: Online Application
  second_CTA_URL: https://successmortgagepartners-com.mysecureloan.com/kristin/applications/page1.php?lng=en
  VR_form: http://oi.vresp.com?fid=e03c9c1295

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "Real Estate Mastermind Strategy Class!"
    CTA_text: "You have an awesome opportunity to learn strategies that will help you take your business to the next level!! Join us on Tuesdays for strategy class with Scott. He shares the latest marketing strategies & interviews top agents around the country, sharing tips that will dramatically impact your business!"
    CTA_link_text: "Register Now"
    CTA_url: http://agentmastermind.com/kristinjamieson/
#
# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/005.jpg
#     CTA_title2: "Looking for a -- MARKET -- Home?"
#     CTA_text2: "Search the entire MLS for your -- MARKET -- home."
#     CTA_link_text2: "Search the MLS"
#     CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    We are a family of trusted mortgage professionals who, through high integrity, take pride in creating lifelong relationships by dedicating ourselves to your mortgage needs. We offer the assistance you need to help in all of your mortgage endeavors. Whether you are consolidating your debt, refinancing your home, or buying your first house, we have the expertise to make it a fast, easy, and enjoyable process. Subscribe to this blog to get the latest news on mortgages and loans and receive expert tips for preparing yourself for your financial future.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/KristinJamiesonMortgageTeam/
  linkedin_url: https://www.linkedin.com/company/65789?trk=prof-exp-company-name
  gplus_url: https://plus.google.com/u/0/b/102869220559365974852
  youtube_url: https://www.youtube.com/channel/UCjiWKkOCn9L5nPYCX_mxIZg
  twitter_url: https://twitter.com/KrisJamiesonSMP
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/
  trulia_url: http://www.trulia.com/
  yelp_url:
  podcast_url: https://itunes.apple.com/us/podcast/success-mortgage-partners-with-kristin-jamieson/id1206042832?mt=2

podcast:
  title: '-- MARKET -- Mortgage and Loan Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more to better prepare yourself for the future.'
  description: 'Our mission at -- CLIENT BRAND -- is to be your best resource for financial advice. Our team of professionals can answer any questions you might have about finance. Subscribe to this blog to get the latest news on finance and receive expert tips for preparing yourself for your financial future.'
  keywords: 'finance, financial planning, retirement, retirement planning, 401K'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text:
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#0B4387'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: rgba(0, 0, 0, .5)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
