audit_header: false
title: -- CLIENT BRAND --
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Heidi Phong
  license_number: "BRE: 01880534"
  about_markdown: |
    Heidi is a licensed California real estate broker with a broad real estate experience from working with buyers and sellers in the residential market, to financing private money, rehab, and property management.

    With her broad spectrum of real estate investment, she can better advises her client's investment needs. Contact her and she will take care of you.
  market: Sacramento
  brand: Heidi Phong Real Estate Team
  brokerage:
  address: 5648 Belleview Ave Sacramento, CA 95824<br>9105 Bruceville, Suite 6A, Elk Grove, CA 95758
  phone: 916-800-3557
  phone_type:
  phone2:
  phone2_type:
  email: heidiphong@gmail.com
  url: www.heidiphonghomes.com

emma_form: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1808304';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.myhomevalue916.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.heidiphonghomes.com/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/005.jpg
    CTA_title: Looking to Buy a Home?
    CTA_text: Search the entire MLS for homes located in -- MARKET --.
    CTA_link_text: Home Search Tool
    CTA_url: http://www.heidiphonghomes.com/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at -- CLIENT BRAND -- is to be your best resource for real estate
    advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/HPRealEstateTeam/?ref=hl
  linkedin_url: https://www.linkedin.com/in/billy-phong-a4b5b31
  gplus_url: https://plus.google.com/u/0/103596051517781127134
  youtube_url: https://www.youtube.com/channel/UCqtmoXbB4pfgh5ZX_8K0WIQ
  twitter_url: https://twitter.com/marketingHPTEAM
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Heidi-Sale/
  trulia_url: http://www.trulia.com/profile/heidi-phong-1-real-estate-team-agent-elk-grove-ca-zgtzyh4j/overview
  yelp_url: http://www.yelp.com/biz/heidi-phong-davis-berk-realty-elk-grove
  podcast_url: https://itunes.apple.com/us/podcast/elk-grove-real-estate-podcast-with-heidi-phong/id1190378434?mt=2

podcast:
  title: Sacramento Real Estate Podcast with Heidi Phong
  categories: Education
  image: http://i.imgur.com/nMXsHvZ.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: http://i.imgur.com/XQDx8aO.png
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: Sacramento Real Estate Video Blog
  hero_background_hex: '#636363'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg

site_colors:
  brand_color: '#B5121B'
  theme_color: '#636363'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: "#000"

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#636363'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
