audit_header: false
title: J. Qualley & Associates Video Blog
description: >-
  If you are looking to buy or sell a home, get all the information and the
  latest updates, tips, and tricks from Jeremy Qualley - your professional --
  MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
client:
  name: Jeremy Qualley
  license_number:
  about_markdown: >-
    A North Dakota native, Jeremy has lived in the surrounding Fargo area nearly
    all his life. Jeremy is dedicated to God, his family, friends, community,
    hard work, and desire to be the best person he can be everyday. From a young
    age, Jeremy was born with Real Estate in his blood with his family coming
    from a Real Estate background.


    Jeremy takes pride in his proven marketing strategies of getting his clients
    and their family out of their current homes and into the future home of
    their dreams. At the same time, his buying strategies of getting First Time
    Home Buyers, families outgrowing their current home and owners wanting to
    downsize are very modernized and effective in this fast paced ever changing
    Real Estate market.
  market: Fargo
  brand: J. Qualley & Associates
  brokerage: eXp Realty
  address: '219 W Main Ave West Fargo, ND 58078'
  phone: 701.306.1823
  phone_type:
  phone2:
  phone2_type:
  email: jeremy.qualley@exprealty.com
  url: www.QualleyHomes.com
CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: 'http://myhousepage.com/fmhomevalues'
  second_CTA_text: Home Search
  second_CTA_URL: >-
    http://www.skrealtyinc.com/idx/search/?OrderBy=-ListPrice&SavedSearch=20111019152906787970000000
emma_form: >-
  <script
  id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1809138';</script><script
  src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: Whatâ€™s Your -- MARKET -- Home Worth?
    CTA_text: >-
      Are you thinking of selling your home or interested in learning about home
      prices in your neighborhood? We can help you.
    CTA_link_text: Free -- MARKET -- Home Value Report
    CTA_url: 'http://myhousepage.com/fmhomevalues'
second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: Looking for a -- MARKET -- Home?
    CTA_text2: Search the entire MLS for your -- MARKET -- home.
    CTA_link_text2: Search the MLS
    CTA_url2: >-
      http://www.skrealtyinc.com/idx/search/?OrderBy=-ListPrice&SavedSearch=20111019152906787970000000
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
welcome_box:
  welcome_headline: Join Our -- MARKET -- VIP List
  welcome_text_markdown: >
    Our mission at  J. Qualley & Associates is to be your best resource for real
    estate advice. Whether you are a buyer, seller, or investor, our team of
    professionals can answer any questions you might have about real estate.
    Subscribe to this blog to get the latest news on local market trends and
    receive expert tips for buying or selling a home.
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/JeremyQ.SKRealty/'
  linkedin_url: 'https://www.linkedin.com/in/jeremyqualley/'
  gplus_url: 'https://plus.google.com/u/0/b/109815595532751966109'
  youtube_url: 'https://www.youtube.com/channel/UCFmsVrYJjvLp8uAwMx-hoqw'
  twitter_url: 'https://twitter.com/JeremyQualley'
  instagram_url:
  pinterest_url:
  zillow_url: 'https://www.zillow.com/profile/Jeremy.Qualley'
  trulia_url: >-
    https://www.trulia.com/profile/jeremy-qualley-agent-west-fargo-nd-zg8ry79s/overview
  yelp_url:
  podcast_url: >-
    https://itunes.apple.com/us/podcast/fargo-real-estate-podcast-with-jeremy-qualley/id1304568871?mt=2
podcast:
  title: Fargo Real Estate Podcast with Jeremy Qualley
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: Jeremy Qualley
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 80
  hero_text: '-- MARKET --'
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#204767'
  theme_color: '#2a2b2e'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'