audit_header: false
title: -- MARKET -- Real Estate Video Blog with -- CLIENT NAME --
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

emma:
  lightbox: <script id="e2ma-embed">window.e2ma=window.e2ma||{};e2ma.accountId='1812585';</script><script src="//dk98ddgl0znzm.cloudfront.net/e2ma.js" async="async"></script>
  form:

client:
  name: James Duffer
  title:
  license_number:
  about_markdown: |
    By keeping his finger on the pulse of the latest trends and movements of the Rhode Island real estate market, James Duffer is able to offer his clients top-notch guidance from start to finish, ensuring the entire process is seamless, efficient and rewarding. 
    
    Specializing in premier Warwick neighborhoods such as Cowesett, Diamond Hill, Gorton Pond, Button Woods and Warwick Neck, where he used to visit his grandparents as a child, James has long admired the city’s architecture and has always been fascinated by the process of how occupants come to fill those residences. Now he’s thrilled to be a key player in that process, which he considers to be both a privilege and a responsibility that he takes quite seriously. 
    
    Prior to joining the world of real estate, as a decorated combat veteran of our nations Army. James Duffer became an expert in figuring out how to provide his men with the resources they needed under the most adverse conditions, to successfully complete their missions. “It starts with fully appreciating each person and then finding creative ways to fulfill their needs that informs how he approaches his work as a real estate representative.” “I treat my clients’ needs and wants as my own when searching for the perfect property or helping them secure the best deal,” he says. Originally from North Kingstown, James received a purple heart from his first tour to Iraq in 2005.
  market:
  brand: Hill Harbor Group
  brokerage:
  address: 694 Main St, East Greenwich, RI 02818
  phone: 401-633-5764
  phone_type:
  phone2:
  phone2_type:
  email: jamesduffer@hillharbor.com
  url: http://www.hillharbor.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.hillharbor.com/cma/property-valuation/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.hillharbor.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.hillharbor.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.hillharbor.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/jamesduffersellsRI/?ref=bookmarks
  linkedin_url:
  gplus_url: https://plus.google.com/110558160395885572993
  youtube_url: https://www.youtube.com/channel/UCNMiyLktPNz2UgryXxpq8xg
  twitter_url: https://twitter.com/JamesDufferHHG
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#656363'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 2px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
